In [ ]:
# 1-қадам — KobeitDos AI платформасының негізі

import random
import ipywidgets as widgets
from IPython.display import display, HTML, clear_output

# Оқушы туралы деректер
student = {
    "name": "",
    "diagnostic_done": False,
    "weak_number": None,
    "diagnostic_results": {},
    "practice_result": None
}

display(HTML("""
<div style="
    background: linear-gradient(135deg, #6C63FF, #42A5F5);
    padding: 30px;
    border-radius: 22px;
    text-align: center;
    color: white;
">
    <h1>🧠 KobeitDos AI</h1>
    <h2>Көбейту кестесін ақылды түрде үйрен!</h2>
    <p style="font-size:18px;">
        📚 Үйрен • 🎮 Ойна • 🧠 Тексер • 🎯 Жаттығу
    </p>
</div>
"""))

print()
print("✅ KobeitDos AI іске қосылды!")
print("🚀 Платформа жұмысқа дайын.")

✅ KobeitDos AI іске қосылды!
🚀 Платформа жұмысқа дайын.

In [ ]:
# 2-қадам — Оқушының аты және негізгі мәзір

# Негізгі жұмыс аймағы
main_area = widgets.Output()

# Оқушы аты
name_input = widgets.Text(
    description="👦 Атың:",
    placeholder="Атыңды жаз...",
    layout=widgets.Layout(width="400px")
)

# Атын сақтау
def name_changed(change):
    student["name"] = change["new"]

name_input.observe(name_changed, names="value")


# Негізгі мәзір батырмалары
learn_btn = widgets.Button(
    description="📚 ҮЙРЕНУ",
    button_style="info",
    layout=widgets.Layout(width="220px", height="50px")
)

game_btn = widgets.Button(
    description="🎮 ОЙЫН",
    button_style="success",
    layout=widgets.Layout(width="220px", height="50px")
)

diagnostic_btn = widgets.Button(
    description="🧠 ДИАГНОСТИКА",
    button_style="warning",
    layout=widgets.Layout(width="220px", height="50px")
)

practice_btn = widgets.Button(
    description="🎯 ЖЕКЕ ЖАТТЫҒУ",
    button_style="primary",
    layout=widgets.Layout(width="220px", height="50px")
)

result_btn = widgets.Button(
    description="📊 МЕНІҢ НӘТИЖЕМ",
    layout=widgets.Layout(width="220px", height="50px")
)


display(HTML("""
<div style="
    background:#F4F6FF;
    padding:18px;
    border-radius:18px;
    margin-top:10px;
">
    <h3>👋 Қош келдің!</h3>
    <p>Алдымен атыңды жаз, содан кейін бөлімді таңда.</p>
</div>
"""))

display(name_input)

display(
    widgets.HBox([
        learn_btn,
        game_btn
    ])
)

display(
    widgets.HBox([
        diagnostic_btn,
        practice_btn
    ])
)

display(result_btn)

# Кейін барлық бөлім осы жерден ашылады
display(main_area)

Text(value='', description='👦 Атың:', layout=Layout(width='400px'), placeholder='Атыңды жаз...')

HBox(children=(Button(button_style='info', description='📚 ҮЙРЕНУ', layout=Layout(height='50px', width='220px')…

HBox(children=(Button(button_style='warning', description='🧠 ДИАГНОСТИКА', layout=Layout(height='50px', width=…

Button(description='📊 МЕНІҢ НӘТИЖЕМ', layout=Layout(height='50px', width='220px'), style=ButtonStyle())

Output()

In [ ]:
# 3-қадам — ҮЙРЕНУ бөлімі (Colab үшін түзетілген)

def open_learn(b):

    with main_area:
        clear_output(wait=True)

        display(HTML("""
        <div style="
            background:#E8EEFF;
            padding:20px;
            border-radius:18px;
            text-align:center;
        ">
            <h2>📚 Көбейту кестесін үйрену</h2>
            <p>Қай санды үйренгің келеді?</p>
        </div>
        """))

        number_select = widgets.Dropdown(
            options=[
                ("Санды таңдаңыз", 0),
                ("2 саны", 2),
                ("3 саны", 3),
                ("4 саны", 4),
                ("5 саны", 5),
                ("6 саны", 6),
                ("7 саны", 7),
                ("8 саны", 8),
                ("9 саны", 9)
            ],
            value=0,
            description="🔢 Сан:",
            layout=widgets.Layout(width="350px")
        )

        display(number_select)

        # Нәтижені HTML виджетінің ішінде көрсетеміз
        table_html = widgets.HTML(
            value="<p>👆 Алдымен санды таңдаңыз.</p>"
        )

        display(table_html)

        def show_table(change):

            n = change["new"]

            if n == 0:
                table_html.value = "<p>👆 Алдымен санды таңдаңыз.</p>"
                return

            rows = ""

            for i in range(1, 11):
                rows += f"""
                <div style="
                    display:inline-block;
                    width:145px;
                    margin:5px;
                    padding:12px;
                    background:white;
                    border:2px solid #6C63FF;
                    border-radius:12px;
                    text-align:center;
                    font-size:19px;
                ">
                    {n} × {i} = <b>{n*i}</b>
                </div>
                """

            table_html.value = f"""
            <div style="
                background:#FFF8E1;
                padding:15px;
                border-radius:15px;
                margin-top:10px;
                text-align:center;
            ">
                <h2>🌟 {n}-ге көбейту кестесі</h2>

                <div>
                    {rows}
                </div>
            </div>
            """

        number_select.observe(show_table, names="value")


# Үйрену батырмасына байланыстырамыз
learn_btn.on_click(open_learn)

In [ ]:
import ipywidgets as widgets
from IPython.display import display, HTML

# Сан таңдау
san = widgets.Dropdown(
    options=[
        ("Санды таңдаңыз", 0),
        ("2", 2),
        ("3", 3),
        ("4", 4),
        ("5", 5),
        ("6", 6),
        ("7", 7),
        ("8", 8),
        ("9", 9)
    ],
    value=0,
    description="🔢 Сан:"
)

# Кесте осы HTML-дың ішінде өзгереді
keste = widgets.HTML(
    value="<h3>👆 Көбейту кестесін таңдаңыз</h3>"
)

def ozgertu(change):
    n = change["new"]

    if n == 0:
        keste.value = "<h3>👆 Көбейту кестесін таңдаңыз</h3>"
        return

    matın = f"""
    <div style="
        padding:20px;
        background:#eef2ff;
        border-radius:18px;
        text-align:center;
    ">
        <h2>📚 {n}-ге көбейту кестесі</h2>
    """

    for i in range(1, 11):
        matın += f"""
        <p style="font-size:22px;">
            {n} × {i} = <b>{n*i}</b>
        </p>
        """

    matın += "</div>"

    keste.value = matın

san.observe(ozgertu, names="value")

display(HTML("<h1>🧠 KobeitDos AI</h1>"))
display(san)
display(keste)

Dropdown(description='🔢 Сан:', options=(('Санды таңдаңыз', 0), ('2', 2), ('3', 3), ('4', 4), ('5', 5), ('6', 6…

HTML(value='<h3>👆 Көбейту кестесін таңдаңыз</h3>')

In [ ]:
# КЕЛЕСІ ҚАДАМ — 🎮 КӨБЕЙТУ ОЙЫНЫ

import random
import ipywidgets as widgets
from IPython.display import display, HTML

# Ойынға арналған мәліметтер
oyin_san = random.randint(2, 9)
oyin_kobeyt = random.randint(2, 9)
durys_zhauap = oyin_san * oyin_kobeyt

# Сұрақ
surak = widgets.HTML(
    value=f"""
    <div style="
        background:#e8f5e9;
        padding:20px;
        border-radius:18px;
        text-align:center;
    ">
        <h2>🎮 Көбейту ойыны</h2>
        <h1>{oyin_san} × {oyin_kobeyt} = ?</h1>
        <p>Жауабыңды жазып, Enter бас.</p>
    </div>
    """
)

# Жауап енгізу
zhauap = widgets.Text(
    placeholder="Жауабыңды жаз...",
    description="✏️ Жауап:"
)

# Нәтиже
habar = widgets.HTML(value="")

def tekser(widget):

    global oyin_san, oyin_kobeyt, durys_zhauap

    try:
        student_answer = int(zhauap.value)
    except:
        habar.value = "<h3>⚠️ Сан енгіз.</h3>"
        return

    if student_answer == durys_zhauap:
        habar.value = """
        <h2 style="color:green;">
        ✅ Дұрыс! Жарайсың!
        </h2>
        """
    else:
        habar.value = f"""
        <h2 style="color:#d32f2f;">
        ❌ Қате. Дұрыс жауап: {durys_zhauap}
        </h2>
        """

# Enter басылғанда тексеру
zhauap.on_submit(tekser)

display(surak)
display(zhauap)
display(habar)

HTML(value='\n    <div style="\n        background:#e8f5e9;\n        padding:20px;\n        border-radius:18px…

Text(value='', description='✏️ Жауап:', placeholder='Жауабыңды жаз...')

HTML(value='')

In [ ]:
# 🎮 5 есептік көбейту ойыны

import random
import ipywidgets as widgets
from IPython.display import display, HTML

# Ойын мәліметтері
game = {
    "question": 1,
    "score": 0,
    "a": 0,
    "b": 0,
    "correct": 0,
    "mistakes": []
}

# Экрандар
game_screen = widgets.HTML()
game_answer = widgets.Text(
    placeholder="Жауабыңды жаз...",
    description="✏️ Жауап:"
)
game_message = widgets.HTML()


def new_question():

    # 5 есеп біткен болса
    if game["question"] > 5:

        percent = game["score"] * 20

        game_screen.value = f"""
        <div style="
            background:#E8F5E9;
            padding:25px;
            border-radius:18px;
            text-align:center;
        ">
            <h1>🏆 Ойын аяқталды!</h1>
            <h2>Ұпай: {game["score"]} / 5</h2>
            <h2>Нәтиже: {percent}%</h2>
        </div>
        """

        game_answer.layout.display = "none"

        if len(game["mistakes"]) == 0:
            game_message.value = """
            <h2 style="color:green; text-align:center;">
            🌟 Керемет! Барлық есеп дұрыс!
            </h2>
            """
        else:
            mistakes_text = "<br>".join(game["mistakes"])

            game_message.value = f"""
            <div style="
                background:#FFF3E0;
                padding:15px;
                border-radius:15px;
            ">
                <h3>📌 Қиналған есептер:</h3>
                {mistakes_text}
            </div>
            """

        return

    # Жаңа есеп
    game["a"] = random.randint(2, 9)
    game["b"] = random.randint(2, 9)
    game["correct"] = game["a"] * game["b"]

    game_screen.value = f"""
    <div style="
        background:#E3F2FD;
        padding:25px;
        border-radius:18px;
        text-align:center;
    ">
        <h2>🎮 KobeitDos AI ойыны</h2>

        <p style="font-size:18px;">
            Сұрақ {game["question"]} / 5
        </p>

        <h1 style="font-size:40px;">
            {game["a"]} × {game["b"]} = ?
        </h1>

        <p>Жауапты жазып, Enter бас.</p>
    </div>
    """

    game_answer.value = ""
    game_message.value = ""


def check_game(widget):

    # Бос жауап болса
    if game_answer.value.strip() == "":
        return

    try:
        answer = int(game_answer.value)
    except:
        game_message.value = """
        <h3 style="color:#d32f2f;">
        ⚠️ Жауапқа сан жаз.
        </h3>
        """
        return

    # Дұрыс жауап
    if answer == game["correct"]:

        game["score"] += 1

        game_message.value = """
        <h3 style="color:green;">
        ✅ Дұрыс!
        </h3>
        """

    # Қате жауап
    else:

        game["mistakes"].append(
            f'{game["a"]} × {game["b"]} = {game["correct"]}'
        )

        game_message.value = f"""
        <h3 style="color:#d32f2f;">
        ❌ Қате. Дұрыс жауап: {game["correct"]}
        </h3>
        """

    game["question"] += 1

    # Келесі есеп
    new_question()


# Enter арқылы жауап беру
game_answer.on_submit(check_game)

# Экранға шығару
display(game_screen)
display(game_answer)
display(game_message)

# Бірінші есеп
new_question()

HTML(value='')

Text(value='', description='✏️ Жауап:', placeholder='Жауабыңды жаз...')

HTML(value='')

In [ ]:
# 🧠 KobeitDos AI — ДИАГНОСТИКА

import random
import ipywidgets as widgets
from IPython.display import display, HTML

# Диагностика деректері
diag = {
    "questions": [],
    "index": 0,
    "results": {n: {"correct": 0, "total": 0} for n in range(2, 10)}
}

# 2-ден 9-ға дейін әр кестеден 2 есеп
for n in range(2, 10):
    for i in range(2):
        b = random.randint(2, 9)
        diag["questions"].append((n, b))

random.shuffle(diag["questions"])

# Экран
diag_screen = widgets.HTML()

diag_answer = widgets.Text(
    placeholder="Жауабыңды жаз...",
    description="✏️ Жауап:"
)

diag_info = widgets.HTML()


def show_diag_question():

    # Барлық 16 есеп аяқталды
    if diag["index"] >= len(diag["questions"]):
        finish_diagnostic()
        return

    a, b = diag["questions"][diag["index"]]

    diag_screen.value = f"""
    <div style="
        background:#FFF3E0;
        padding:25px;
        border-radius:18px;
        text-align:center;
    ">
        <h2>🧠 KobeitDos AI диагностикасы</h2>

        <p style="font-size:18px;">
            Сұрақ {diag["index"] + 1} / 16
        </p>

        <h1 style="font-size:40px;">
            {a} × {b} = ?
        </h1>

        <p>Жауапты жазып, Enter бас.</p>
    </div>
    """

    diag_answer.value = ""
    diag_info.value = ""


def check_diag(widget):

    if diag_answer.value.strip() == "":
        return

    try:
        answer = int(diag_answer.value)
    except:
        diag_info.value = """
        <h3 style="color:red;">
        ⚠️ Тек сан енгіз.
        </h3>
        """
        return

    a, b = diag["questions"][diag["index"]]
    correct_answer = a * b

    # Осы кестеге бір сұрақ қосылды
    diag["results"][a]["total"] += 1

    # Дұрыс болса
    if answer == correct_answer:
        diag["results"][a]["correct"] += 1

    # Келесі сұрақ
    diag["index"] += 1
    show_diag_question()


def finish_diagnostic():

    global diagnostic_percent
    global weakest_number

    diagnostic_percent = {}

    for n in range(2, 10):

        correct = diag["results"][n]["correct"]
        total = diag["results"][n]["total"]

        if total > 0:
            percent = int((correct / total) * 100)
        else:
            percent = 0

        diagnostic_percent[n] = percent

    # Ең төмен нәтиже
    weakest_number = min(
        diagnostic_percent,
        key=diagnostic_percent.get
    )

    rows = ""

    for n in range(2, 10):

        p = diagnostic_percent[n]

        rows += f"""
        <div style="
            margin:7px;
            padding:10px;
            background:white;
            border-radius:10px;
            font-size:18px;
        ">
            {n}-ге көбейту:
            <b>{p}%</b>
        </div>
        """

    diag_screen.value = f"""
    <div style="
        background:#E8F5E9;
        padding:25px;
        border-radius:18px;
        text-align:center;
    ">

        <h1>📊 Диагностика аяқталды!</h1>

        {rows}

        <hr>

        <h2>
            🤖 KobeitDos AI анықтады:
        </h2>

        <h2 style="color:#d32f2f;">
            Саған {weakest_number}-ге көбейтуді
            көбірек жаттықтыру керек.
        </h2>

    </div>
    """

    diag_answer.layout.display = "none"
    diag_info.value = ""


# Enter арқылы тексеру
diag_answer.on_submit(check_diag)

# Экранға шығару
display(diag_screen)
display(diag_answer)
display(diag_info)

# Бірінші сұрақ
show_diag_question()

HTML(value='')

Text(value='', description='✏️ Жауап:', placeholder='Жауабыңды жаз...')

HTML(value='')

In [ ]:
# 🎯 KobeitDos AI — ЖЕКЕ ЖАТТЫҒУ

import random
import ipywidgets as widgets
from IPython.display import display, HTML

# Жеке жаттығу деректері
practice = {
    "question": 1,
    "score": 0,
    "number": weakest_number,
    "b": 0,
    "correct": 0,
    "mistakes": []
}

# Экран
practice_screen = widgets.HTML()

practice_answer = widgets.Text(
    placeholder="Жауабыңды жаз...",
    description="✏️ Жауап:"
)

practice_info = widgets.HTML()


def show_practice_question():

    # 5 сұрақ аяқталса
    if practice["question"] > 5:
        finish_practice()
        return

    # Әлсіз кестеден есеп
    practice["b"] = random.randint(2, 9)

    practice["correct"] = (
        practice["number"] * practice["b"]
    )

    practice_screen.value = f"""
    <div style="
        background:#F3E5F5;
        padding:25px;
        border-radius:18px;
        text-align:center;
    ">

        <h2>🎯 Жеке жаттығу</h2>

        <p>
            🤖 KobeitDos AI саған
            <b>{practice["number"]}-ге көбейтуді</b>
            жаттықтыруды ұсынады.
        </p>

        <p style="font-size:18px;">
            Сұрақ {practice["question"]} / 5
        </p>

        <h1 style="font-size:40px;">
            {practice["number"]} × {practice["b"]} = ?
        </h1>

        <p>
            Жауабыңды жазып, Enter бас.
        </p>

    </div>
    """

    practice_answer.value = ""
    practice_info.value = ""


def check_practice(widget):

    if practice_answer.value.strip() == "":
        return

    try:
        answer = int(practice_answer.value)

    except:
        practice_info.value = """
        <h3 style="color:red;">
            ⚠️ Тек сан енгіз.
        </h3>
        """
        return

    # Дұрыс жауап
    if answer == practice["correct"]:

        practice["score"] += 1

    # Қате жауап
    else:

        practice["mistakes"].append(
            f'{practice["number"]} × '
            f'{practice["b"]} = '
            f'{practice["correct"]}'
        )

    practice["question"] += 1

    show_practice_question()


def finish_practice():

    global practice_percent

    practice_percent = practice["score"] * 20

    # Диагностикадағы бастапқы нәтиже
    before_percent = diagnostic_percent[
        practice["number"]
    ]

    difference = practice_percent - before_percent

    if difference > 0:
        message = f"""
        🌟 Нәтижең {difference}% жақсарды!
        """
    elif difference == 0:
        message = """
        👍 Нәтижең тұрақты. Тағы жаттығып көр!
        """
    else:
        message = """
        💪 Бұл кестені тағы бір рет қайталап көрейік.
        """

    practice_screen.value = f"""
    <div style="
        background:#E8F5E9;
        padding:25px;
        border-radius:18px;
        text-align:center;
    ">

        <h1>🎉 Жеке жаттығу аяқталды!</h1>

        <h2>
            {practice["number"]}-ге көбейту
        </h2>

        <p style="font-size:20px;">
            🧠 Диагностика:
            <b>{before_percent}%</b>
        </p>

        <p style="font-size:20px;">
            🎯 Жаттығудан кейін:
            <b>{practice_percent}%</b>
        </p>

        <h2>
            {message}
        </h2>

    </div>
    """

    practice_answer.layout.display = "none"
    practice_info.value = ""


# Enter арқылы жауап беру
practice_answer.on_submit(check_practice)

# Экранға шығару
display(practice_screen)
display(practice_answer)
display(practice_info)

# Бірінші есеп
show_practice_question()

NameError: name 'weakest_number' is not defined

In [ ]:
# 📊 KobeitDos AI — ОҚУШЫ НӘТИЖЕСІ

import ipywidgets as widgets
from IPython.display import display, HTML

# Диагностика нәтижелерінен жолдар жасау
result_rows = ""

for n in range(2, 10):

    percent = diagnostic_percent[n]

    if percent == 100:
        belgi = "🌟 Өте жақсы"
    elif percent >= 50:
        belgi = "👍 Жақсы"
    else:
        belgi = "📚 Жаттығу керек"

    result_rows += f"""
    <tr>
        <td style="padding:10px; border:1px solid #ddd;">
            {n}-ге көбейту
        </td>

        <td style="padding:10px; border:1px solid #ddd;">
            <b>{percent}%</b>
        </td>

        <td style="padding:10px; border:1px solid #ddd;">
            {belgi}
        </td>
    </tr>
    """

# Әлсіз кестенің бастапқы нәтижесі
before = diagnostic_percent[weakest_number]

# Жеке жаттығудан кейінгі нәтиже
after = practice_percent

# Өзгеріс
change = after - before

if change > 0:
    ai_text = f"""
    🌟 Жарайсың! Нәтижең {change}% жақсарды.
    """
elif change == 0:
    ai_text = """
    👍 Нәтижең өзгерген жоқ. Тағы жаттығу пайдалы болады.
    """
else:
    ai_text = """
    📚 Бұл кестені тағы қайталап жаттықтыру ұсынылады.
    """

# Нәтижені экранға шығару
result_html = widgets.HTML(
    value=f"""
    <div style="
        background:#F7F8FF;
        padding:25px;
        border-radius:20px;
    ">

        <h1 style="text-align:center;">
            📊 KobeitDos AI — Менің нәтижем
        </h1>

        <h2 style="text-align:center;">
            🧠 Диагностика нәтижесі
        </h2>

        <table style="
            width:100%;
            border-collapse:collapse;
            background:white;
            text-align:center;
        ">

            <tr style="background:#E8EEFF;">
                <th style="padding:10px; border:1px solid #ddd;">
                    Кесте
                </th>

                <th style="padding:10px; border:1px solid #ddd;">
                    Нәтиже
                </th>

                <th style="padding:10px; border:1px solid #ddd;">
                    Бағалау
                </th>
            </tr>

            {result_rows}

        </table>

        <br>

        <div style="
            background:#FFF3E0;
            padding:18px;
            border-radius:15px;
            text-align:center;
        ">

            <h2>🤖 AI ұсынысы</h2>

            <p style="font-size:19px;">
                Ең көп жаттығуды қажет ететін кесте:
                <b>{weakest_number}-ге көбейту</b>
            </p>

        </div>

        <br>

        <div style="
            background:#E8F5E9;
            padding:18px;
            border-radius:15px;
            text-align:center;
        ">

            <h2>🎯 Менің өзгерісім</h2>

            <p style="font-size:20px;">
                Диагностикаға дейін:
                <b>{before}%</b>
            </p>

            <p style="font-size:20px;">
                Жеке жаттығудан кейін:
                <b>{after}%</b>
            </p>

            <h2>
                {ai_text}
            </h2>

        </div>

    </div>
    """
)

display(result_html)

NameError: name 'diagnostic_percent' is not defined

In [ ]:
# 🧠 KobeitDos AI — НЕГІЗГІ МӘЗІР
# Colab-та тұрақты жұмыс істейтін Dropdown нұсқасы

import ipywidgets as widgets
from IPython.display import display, HTML

# Негізгі тақырып
platform_title = widgets.HTML(
    value="""
    <div style="
        background:linear-gradient(135deg,#6C63FF,#42A5F5);
        padding:25px;
        border-radius:20px;
        text-align:center;
        color:white;
    ">
        <h1>🧠 KobeitDos AI</h1>
        <h3>Көбейту кестесін ақылды түрде үйрен!</h3>
    </div>
    """
)

# Бөлім таңдау
bolim = widgets.Dropdown(
    options=[
        ("🏠 Басты бет", "home"),
        ("📚 Үйрену", "learn"),
        ("🎮 Ойын", "game"),
        ("🧠 Диагностика", "diagnostic"),
        ("🎯 Жеке жаттығу", "practice"),
        ("📊 Менің нәтижем", "result")
    ],
    value="home",
    description="📌 Бөлім:",
    layout=widgets.Layout(width="400px")
)

# Негізгі экран
platform_screen = widgets.HTML()


def bolim_auystyr(change):

    section = change["new"]

    if section == "home":

        platform_screen.value = """
        <div style="
            background:#F4F6FF;
            padding:25px;
            border-radius:18px;
            text-align:center;
        ">
            <h2>👋 Қош келдің!</h2>

            <p style="font-size:18px;">
                KobeitDos AI көбейту кестесін
                үйренуге көмектеседі.
            </p>

            <p>
                📚 Үйрену • 🎮 Ойын • 🧠 Диагностика
                • 🎯 Жеке жаттығу • 📊 Нәтиже
            </p>
        </div>
        """

    elif section == "learn":

        platform_screen.value = """
        <div style="
            background:#E8EEFF;
            padding:25px;
            border-radius:18px;
            text-align:center;
        ">
            <h1>📚 ҮЙРЕНУ</h1>
            <p>Көбейту кестесін үйрену бөлімі</p>
            <h3>✅ Бөлім ашылды</h3>
        </div>
        """

    elif section == "game":

        platform_screen.value = """
        <div style="
            background:#E8F5E9;
            padding:25px;
            border-radius:18px;
            text-align:center;
        ">
            <h1>🎮 ОЙЫН</h1>
            <p>Көбейту ойыны бөлімі</p>
            <h3>✅ Бөлім ашылды</h3>
        </div>
        """

    elif section == "diagnostic":

        platform_screen.value = """
        <div style="
            background:#FFF3E0;
            padding:25px;
            border-radius:18px;
            text-align:center;
        ">
            <h1>🧠 ДИАГНОСТИКА</h1>
            <p>Оқушының білімін анықтау бөлімі</p>
            <h3>✅ Бөлім ашылды</h3>
        </div>
        """

    elif section == "practice":

        platform_screen.value = """
        <div style="
            background:#F3E5F5;
            padding:25px;
            border-radius:18px;
            text-align:center;
        ">
            <h1>🎯 ЖЕКЕ ЖАТТЫҒУ</h1>
            <p>Жеке тапсырмалар бөлімі</p>
            <h3>✅ Бөлім ашылды</h3>
        </div>
        """

    elif section == "result":

        platform_screen.value = """
        <div style="
            background:#E0F7FA;
            padding:25px;
            border-radius:18px;
            text-align:center;
        ">
            <h1>📊 МЕНІҢ НӘТИЖЕМ</h1>
            <p>Оқушы нәтижелері бөлімі</p>
            <h3>✅ Бөлім ашылды</h3>
        </div>
        """


# Мәзір өзгерген кезде
bolim.observe(
    bolim_auystyr,
    names="value"
)

# Экранға шығару
display(platform_title)
display(bolim)
display(platform_screen)

# Басты бетті бірден көрсету
bolim_auystyr({"new": "home"})

In [ ]:
# 🎮 ОЙЫНДЫ ДАЙЫНДАУ

import random
import ipywidgets as widgets
from IPython.display import display

# Ойын деректері
menu_game = {
    "question": 1,
    "score": 0,
    "a": 0,
    "b": 0,
    "correct": 0
}

# Ойын экраны
menu_game_screen = widgets.HTML()

# Жауап енгізу
menu_game_answer = widgets.Text(
    placeholder="Жауабыңды жаз...",
    description="✏️ Жауап:"
)

# Хабарлама
menu_game_message = widgets.HTML()


def menu_new_question():

    # 5 сұрақ аяқталса
    if menu_game["question"] > 5:

        percent = menu_game["score"] * 20

        menu_game_screen.value = f"""
        <div style="
            background:#E8F5E9;
            padding:25px;
            border-radius:18px;
            text-align:center;
        ">
            <h1>🏆 Ойын аяқталды!</h1>

            <h2>
                Ұпай: {menu_game["score"]} / 5
            </h2>

            <h2>
                Нәтиже: {percent}%
            </h2>
        </div>
        """

        menu_game_answer.layout.display = "none"
        return

    # Жаңа есеп
    menu_game["a"] = random.randint(2, 9)
    menu_game["b"] = random.randint(2, 9)

    menu_game["correct"] = (
        menu_game["a"] * menu_game["b"]
    )

    menu_game_screen.value = f"""
    <div style="
        background:#E8F5E9;
        padding:25px;
        border-radius:18px;
        text-align:center;
    ">

        <h2>🎮 KobeitDos AI — Ойын</h2>

        <h3>
            Сұрақ {menu_game["question"]} / 5
        </h3>

        <h1 style="font-size:42px;">
            {menu_game["a"]} × {menu_game["b"]} = ?
        </h1>

        <p>
            Жауабыңды жазып, Enter бас
        </p>

    </div>
    """

    menu_game_answer.value = ""
    menu_game_message.value = ""


def menu_check_answer(widget):

    if menu_game_answer.value.strip() == "":
        return

    try:
        answer = int(menu_game_answer.value)
    except:
        menu_game_message.value = """
        <h3 style="color:red;">
            ⚠️ Тек сан енгіз.
        </h3>
        """
        return

    if answer == menu_game["correct"]:

        menu_game["score"] += 1

        menu_game_message.value = """
        <h3 style="color:green;">
            ✅ Дұрыс!
        </h3>
        """

    else:

        menu_game_message.value = f"""
        <h3 style="color:red;">
            ❌ Қате.
            Дұрыс жауап:
            {menu_game["correct"]}
        </h3>
        """

    menu_game["question"] += 1

    menu_new_question()


# Enter пернесін байланыстыру
menu_game_answer.on_submit(menu_check_answer)

# Алғашқы есеп
menu_new_question()

# ТЕКСЕРУ ҮШІН УАҚЫТША ШЫҒАРАМЫЗ
display(menu_game_screen)
display(menu_game_answer)
display(menu_game_message)

HTML(value='\n    <div style="\n        background:#E8F5E9;\n        padding:25px;\n        border-radius:18px…

Text(value='', description='✏️ Жауап:', placeholder='Жауабыңды жаз...')

HTML(value='')

In [ ]:
# 🎮 ОЙЫНДЫ НЕГІЗГІ МӘЗІРМЕН БАЙЛАНЫСТЫРУ

def main_menu_change(change):

    section = change["new"]

    # 🏠 БАСТЫ БЕТ
    if section == "home":

        platform_screen.value = """
        <div style="
            background:#F4F6FF;
            padding:25px;
            border-radius:18px;
            text-align:center;
        ">
            <h1>🏠 Басты бет</h1>
            <h2>🧠 KobeitDos AI</h2>
            <p>Қажетті бөлімді жоғарыдан таңда.</p>
        </div>
        """

        menu_game_screen.layout.display = "none"
        menu_game_answer.layout.display = "none"
        menu_game_message.layout.display = "none"


    # 📚 ҮЙРЕНУ
    elif section == "learn":

        platform_screen.value = """
        <div style="
            background:#E8EEFF;
            padding:25px;
            border-radius:18px;
            text-align:center;
        ">
            <h1>📚 ҮЙРЕНУ</h1>
            <p>Көбейту кестесін үйрену бөлімі</p>
            <h3>✅ Бөлім ашылды</h3>
        </div>
        """

        menu_game_screen.layout.display = "none"
        menu_game_answer.layout.display = "none"
        menu_game_message.layout.display = "none"


    # 🎮 ОЙЫН
    elif section == "game":

        # Ойынды қайта бастау
        menu_game["question"] = 1
        menu_game["score"] = 0

        menu_game_screen.layout.display = ""
        menu_game_answer.layout.display = ""
        menu_game_message.layout.display = ""

        platform_screen.value = """
        <div style="
            background:#E8F5E9;
            padding:12px;
            border-radius:18px;
            text-align:center;
        ">
            <h2>🎮 Ойын басталды!</h2>
        </div>
        """

        menu_new_question()


    # 🧠 ДИАГНОСТИКА
    elif section == "diagnostic":

        platform_screen.value = """
        <div style="
            background:#FFF3E0;
            padding:25px;
            border-radius:18px;
            text-align:center;
        ">
            <h1>🧠 ДИАГНОСТИКА</h1>
            <p>Диагностика келесі қадамда қосылады.</p>
        </div>
        """

        menu_game_screen.layout.display = "none"
        menu_game_answer.layout.display = "none"
        menu_game_message.layout.display = "none"


    # 🎯 ЖЕКЕ ЖАТТЫҒУ
    elif section == "practice":

        platform_screen.value = """
        <div style="
            background:#F3E5F5;
            padding:25px;
            border-radius:18px;
            text-align:center;
        ">
            <h1>🎯 ЖЕКЕ ЖАТТЫҒУ</h1>
            <p>Жеке жаттығу келесі қадамда қосылады.</p>
        </div>
        """

        menu_game_screen.layout.display = "none"
        menu_game_answer.layout.display = "none"
        menu_game_message.layout.display = "none"


    # 📊 НӘТИЖЕ
    elif section == "result":

        platform_screen.value = """
        <div style="
            background:#E0F7FA;
            padding:25px;
            border-radius:18px;
            text-align:center;
        ">
            <h1>📊 МЕНІҢ НӘТИЖЕМ</h1>
            <p>Нәтижелер кейін осы жерде көрсетіледі.</p>
        </div>
        """

        menu_game_screen.layout.display = "none"
        menu_game_answer.layout.display = "none"
        menu_game_message.layout.display = "none"


# Бұрынғы мәзір функциясын ажыратамыз
bolim.unobserve(bolim_auystyr, names="value")

# Жаңа функцияны байланыстырамыз
bolim.observe(main_menu_change, names="value")

# Ойын виджеттерін мәзірдің астына орналастырамыз
display(menu_game_screen)
display(menu_game_answer)
display(menu_game_message)

# Қазір ойындарды жасырып қоямыз
menu_game_screen.layout.display = "none"
menu_game_answer.layout.display = "none"
menu_game_message.layout.display = "none"

# Басты бетке қайтарамыз
bolim.value = "home"
main_menu_change({"new": "home"})

NameError: name 'bolim' is not defined

In [ ]:
# 🎮 ОЙЫН ЭКРАНЫН ТҮЗЕТУ
# Ескі Output қолданылмайды

import random
import ipywidgets as widgets
from IPython.display import display

# Жаңа ойын аймағы
game_box = widgets.VBox()
game_html = widgets.HTML()

game_input = widgets.Text(
    description="✏️ Жауап:",
    placeholder="Жауабыңды жазып, Enter бас...",
    layout=widgets.Layout(width="450px")
)

game_feedback = widgets.HTML()

game_data = {
    "q": 1,
    "score": 0,
    "a": 0,
    "b": 0,
    "correct": 0
}


def game_question():

    if game_data["q"] > 5:

        percent = game_data["score"] * 20

        game_html.value = f"""
        <div style="
            background:#E8F5E9;
            padding:25px;
            border-radius:18px;
            text-align:center;
        ">
            <h1>🏆 Ойын аяқталды!</h1>
            <h2>Ұпай: {game_data["score"]} / 5</h2>
            <h2>Нәтиже: {percent}%</h2>
        </div>
        """

        game_input.layout.display = "none"
        return

    game_data["a"] = random.randint(2, 9)
    game_data["b"] = random.randint(2, 9)

    game_data["correct"] = (
        game_data["a"] * game_data["b"]
    )

    game_html.value = f"""
    <div style="
        background:#E8F5E9;
        padding:25px;
        border-radius:18px;
        text-align:center;
    ">

        <h2>🎮 KobeitDos AI — Ойын</h2>

        <h3>
            Сұрақ {game_data["q"]} / 5
        </h3>

        <h1 style="font-size:42px;">
            {game_data["a"]} × {game_data["b"]} = ?
        </h1>

        <p>
            Жауабыңды жазып, Enter бас
        </p>

    </div>
    """

    game_input.value = ""
    game_feedback.value = ""


def game_enter(widget):

    try:
        answer = int(game_input.value)
    except:
        game_feedback.value = """
        <h3 style="color:red;">
        ⚠️ Тек сан енгіз.
        </h3>
        """
        return

    if answer == game_data["correct"]:
        game_data["score"] += 1

    game_data["q"] += 1
    game_question()


game_input.on_submit(game_enter)

# Бір блоктың ішіне жинау
game_box.children = (
    game_html,
    game_input,
    game_feedback
)

# Алдымен жасырамыз
game_box.layout.display = "none"

# Мәзірдің дәл астына шығару
display(game_box)

In [ ]:
game_box.layout.display = ""
game_data["q"] = 1
game_data["score"] = 0
game_input.layout.display = ""
game_question()

NameError: name 'game_box' is not defined

In [ ]:
# ==========================================================
# 🧠 KobeitDos AI — ТҰТАС ПЛАТФОРМА
# 1-нұсқа: 📚 Үйрену + 🎮 Ойын
# ==========================================================

import random
import ipywidgets as widgets
from IPython.display import display


# ----------------------------------------------------------
# 1. ПЛАТФОРМА ТАҚЫРЫБЫ
# ----------------------------------------------------------

title = widgets.HTML("""
<div style="
    background:linear-gradient(135deg,#667eea,#42a5f5);
    padding:25px;
    border-radius:22px;
    text-align:center;
    color:white;
">
    <h1>🧠 KobeitDos AI</h1>
    <h3>Көбейту кестесін ақылды түрде үйрен!</h3>
</div>
""")


# ----------------------------------------------------------
# 2. НЕГІЗГІ МӘЗІР
# ----------------------------------------------------------

menu = widgets.Dropdown(
    options=[
        ("🏠 Басты бет", "home"),
        ("📚 Үйрену", "learn"),
        ("🎮 Ойын", "game")
    ],
    value="home",
    description="📌 Бөлім:",
    layout=widgets.Layout(width="420px")
)


# ----------------------------------------------------------
# 3. БАСТЫ БЕТ
# ----------------------------------------------------------

home_html = widgets.HTML("""
<div style="
    background:#F4F6FF;
    padding:25px;
    border-radius:18px;
    text-align:center;
">
    <h2>👋 Қош келдің!</h2>

    <p style="font-size:18px;">
        KobeitDos AI көбейту кестесін
        үйренуге көмектеседі.
    </p>

    <h3>
        📚 Үйрену &nbsp;&nbsp; 🎮 Ойын
    </h3>

    <p>
        Жоғарыдағы мәзірден бөлімді таңда.
    </p>
</div>
""")


# ==========================================================
# 📚 ҮЙРЕНУ БӨЛІМІ
# ==========================================================

learn_title = widgets.HTML("""
<div style="
    background:#E8EEFF;
    padding:18px;
    border-radius:18px;
    text-align:center;
">
    <h2>📚 Көбейту кестесін үйрену</h2>
    <p>Қай санды үйренгің келеді?</p>
</div>
""")


learn_number = widgets.Dropdown(
    options=[
        ("Санды таңда", 0),
        ("2 саны", 2),
        ("3 саны", 3),
        ("4 саны", 4),
        ("5 саны", 5),
        ("6 саны", 6),
        ("7 саны", 7),
        ("8 саны", 8),
        ("9 саны", 9)
    ],
    value=0,
    description="🔢 Сан:",
    layout=widgets.Layout(width="350px")
)


learn_table = widgets.HTML(
    "<h3>👆 Алдымен санды таңда.</h3>"
)


def change_table(change):

    n = change["new"]

    if n == 0:
        learn_table.value = """
        <h3>👆 Алдымен санды таңда.</h3>
        """
        return

    cards = ""

    for i in range(1, 11):

        cards += f"""
        <div style="
            display:inline-block;
            width:145px;
            margin:6px;
            padding:12px;
            border:2px solid #667eea;
            border-radius:13px;
            background:white;
            font-size:19px;
        ">
            {n} × {i} = <b>{n*i}</b>
        </div>
        """

    learn_table.value = f"""
    <div style="
        background:#FFF8E1;
        padding:20px;
        border-radius:18px;
        text-align:center;
    ">

        <h2>🌟 {n}-ге көбейту кестесі</h2>

        {cards}

    </div>
    """


learn_number.observe(
    change_table,
    names="value"
)


learn_box = widgets.VBox([
    learn_title,
    learn_number,
    learn_table
])


# ==========================================================
# 🎮 ОЙЫН БӨЛІМІ
# ==========================================================

game_data = {
    "question": 1,
    "score": 0,
    "a": 0,
    "b": 0,
    "correct": 0,
    "mistakes": []
}


game_html = widgets.HTML()

game_input = widgets.Text(
    description="✏️ Жауап:",
    placeholder="Жауабыңды жазып, Enter бас...",
    layout=widgets.Layout(width="450px")
)

game_message = widgets.HTML()


def new_game_question():

    # 5 сұрақ аяқталды
    if game_data["question"] > 5:

        percent = game_data["score"] * 20

        if len(game_data["mistakes"]) == 0:

            mistake_text = """
            <h3 style="color:green;">
                🌟 Барлық есеп дұрыс!
            </h3>
            """

        else:

            mistakes = "<br>".join(
                game_data["mistakes"]
            )

            mistake_text = f"""
            <div style="
                background:#FFF3E0;
                padding:12px;
                border-radius:12px;
            ">
                <b>📌 Қиналған есептер:</b>
                <br>
                {mistakes}
            </div>
            """

        game_html.value = f"""
        <div style="
            background:#E8F5E9;
            padding:25px;
            border-radius:18px;
            text-align:center;
        ">

            <h1>🏆 Ойын аяқталды!</h1>

            <h2>
                Ұпай: {game_data["score"]} / 5
            </h2>

            <h2>
                Нәтиже: {percent}%
            </h2>

            {mistake_text}

        </div>
        """

        game_input.layout.display = "none"
        game_message.value = ""

        return


    # Жаңа есеп
    game_data["a"] = random.randint(2, 9)
    game_data["b"] = random.randint(2, 9)

    game_data["correct"] = (
        game_data["a"] * game_data["b"]
    )

    game_html.value = f"""
    <div style="
        background:#E8F5E9;
        padding:25px;
        border-radius:18px;
        text-align:center;
    ">

        <h2>🎮 KobeitDos AI — Ойын</h2>

        <h3>
            Сұрақ {game_data["question"]} / 5
        </h3>

        <h1 style="font-size:42px;">
            {game_data["a"]} ×
            {game_data["b"]} = ?
        </h1>

        <p>
            Жауабыңды жазып,
            Enter бас.
        </p>

    </div>
    """

    game_input.value = ""
    game_message.value = ""


def check_game(widget):

    if game_input.value.strip() == "":
        return

    try:
        answer = int(game_input.value)

    except:

        game_message.value = """
        <h3 style="color:red;">
            ⚠️ Тек сан енгіз.
        </h3>
        """

        return


    if answer == game_data["correct"]:

        game_data["score"] += 1

    else:

        game_data["mistakes"].append(
            f'{game_data["a"]} × '
            f'{game_data["b"]} = '
            f'{game_data["correct"]}'
        )


    game_data["question"] += 1

    new_game_question()


game_input.on_submit(check_game)


game_box = widgets.VBox([
    game_html,
    game_input,
    game_message
])


def start_game():

    game_data["question"] = 1
    game_data["score"] = 0
    game_data["mistakes"] = []

    game_input.layout.display = ""

    new_game_question()


# ==========================================================
# 4. БӨЛІМДЕРДІ АУЫСТЫРУ
# ==========================================================

def change_section(change):

    section = change["new"]

    # Барлығын жасырамыз
    home_html.layout.display = "none"
    learn_box.layout.display = "none"
    game_box.layout.display = "none"


    # Басты бет
    if section == "home":

        home_html.layout.display = ""


    # Үйрену
    elif section == "learn":

        learn_box.layout.display = ""


    # Ойын
    elif section == "game":

        game_box.layout.display = ""

        start_game()


menu.observe(
    change_section,
    names="value"
)


# ==========================================================
# 5. ПЛАТФОРМАНЫ БІР РЕТ ҚАНА ШЫҒАРУ
# ==========================================================

platform = widgets.VBox([
    title,
    menu,
    home_html,
    learn_box,
    game_box
])


display(platform)


# Алғаш ашылғанда
learn_box.layout.display = "none"
game_box.layout.display = "none"
home_html.layout.display = ""

VBox(children=(HTML(value='\n<div style="\n    background:linear-gradient(135deg,#667eea,#42a5f5);\n    paddin…

In [ ]:
# ==========================================================
# 🧠 KobeitDos AI
# 📚 Үйрену + 🎮 Ойын + 🧠 Диагностика
# ==========================================================

import random
import ipywidgets as widgets
from IPython.display import display


# ==========================================================
# 1. ТАҚЫРЫП
# ==========================================================

app_title = widgets.HTML("""
<div style="
    background:linear-gradient(135deg,#667eea,#42a5f5);
    padding:25px;
    border-radius:22px;
    text-align:center;
    color:white;
">
    <h1>🧠 KobeitDos AI</h1>
    <h3>Көбейту кестесін ақылды түрде үйрен!</h3>
</div>
""")


# ==========================================================
# 2. МӘЗІР
# ==========================================================

app_menu = widgets.Dropdown(
    options=[
        ("🏠 Басты бет", "home"),
        ("📚 Үйрену", "learn"),
        ("🎮 Ойын", "game"),
        ("🧠 Диагностика", "diagnostic")
    ],
    value="home",
    description="📌 Бөлім:",
    layout=widgets.Layout(width="430px")
)


# ==========================================================
# 🏠 БАСТЫ БЕТ
# ==========================================================

home_box = widgets.HTML("""
<div style="
    background:#F4F6FF;
    padding:25px;
    border-radius:18px;
    text-align:center;
">
    <h2>👋 Қош келдің!</h2>

    <p style="font-size:18px;">
        KobeitDos AI көбейту кестесін
        үйренуге көмектеседі.
    </p>

    <h3>
        📚 Үйрену &nbsp;&nbsp;
        🎮 Ойын &nbsp;&nbsp;
        🧠 Диагностика
    </h3>

    <p>
        Жоғарыдағы мәзірден бөлімді таңда.
    </p>
</div>
""")


# ==========================================================
# 📚 ҮЙРЕНУ
# ==========================================================

learn_title2 = widgets.HTML("""
<div style="
    background:#E8EEFF;
    padding:18px;
    border-radius:18px;
    text-align:center;
">
    <h2>📚 Көбейту кестесін үйрену</h2>
    <p>Қай санды үйренгің келеді?</p>
</div>
""")


learn_select2 = widgets.Dropdown(
    options=[
        ("Санды таңда", 0),
        ("2 саны", 2),
        ("3 саны", 3),
        ("4 саны", 4),
        ("5 саны", 5),
        ("6 саны", 6),
        ("7 саны", 7),
        ("8 саны", 8),
        ("9 саны", 9)
    ],
    value=0,
    description="🔢 Сан:",
    layout=widgets.Layout(width="350px")
)


learn_html2 = widgets.HTML(
    "<h3>👆 Алдымен санды таңда.</h3>"
)


def learn_change2(change):

    n = change["new"]

    if n == 0:
        learn_html2.value = """
        <h3>👆 Алдымен санды таңда.</h3>
        """
        return

    cards = ""

    for i in range(1, 11):

        cards += f"""
        <div style="
            display:inline-block;
            width:145px;
            margin:6px;
            padding:12px;
            border:2px solid #667eea;
            border-radius:13px;
            background:white;
            font-size:19px;
        ">
            {n} × {i} = <b>{n*i}</b>
        </div>
        """

    learn_html2.value = f"""
    <div style="
        background:#FFF8E1;
        padding:20px;
        border-radius:18px;
        text-align:center;
    ">
        <h2>🌟 {n}-ге көбейту кестесі</h2>
        {cards}
    </div>
    """


learn_select2.observe(
    learn_change2,
    names="value"
)


learn_box2 = widgets.VBox([
    learn_title2,
    learn_select2,
    learn_html2
])


# ==========================================================
# 🎮 ОЙЫН
# ==========================================================

game2 = {
    "q": 1,
    "score": 0,
    "a": 0,
    "b": 0,
    "correct": 0,
    "mistakes": []
}


game_html2 = widgets.HTML()

game_input2 = widgets.Text(
    description="✏️ Жауап:",
    placeholder="Жауабыңды жазып, Enter бас...",
    layout=widgets.Layout(width="450px")
)

game_message2 = widgets.HTML()


def game_question2():

    if game2["q"] > 5:

        percent = game2["score"] * 20

        if len(game2["mistakes"]) == 0:

            mistakes_html = """
            <h3 style="color:green;">
                🌟 Барлық есеп дұрыс!
            </h3>
            """

        else:

            mistake_list = "<br>".join(
                game2["mistakes"]
            )

            mistakes_html = f"""
            <div style="
                background:#FFF3E0;
                padding:12px;
                border-radius:12px;
            ">
                <b>📌 Қиналған есептер:</b>
                <br>
                {mistake_list}
            </div>
            """

        game_html2.value = f"""
        <div style="
            background:#E8F5E9;
            padding:25px;
            border-radius:18px;
            text-align:center;
        ">

            <h1>🏆 Ойын аяқталды!</h1>

            <h2>
                Ұпай: {game2["score"]} / 5
            </h2>

            <h2>
                Нәтиже: {percent}%
            </h2>

            {mistakes_html}

        </div>
        """

        game_input2.layout.display = "none"
        game_message2.value = ""

        return


    game2["a"] = random.randint(2, 9)
    game2["b"] = random.randint(2, 9)

    game2["correct"] = (
        game2["a"] * game2["b"]
    )

    game_html2.value = f"""
    <div style="
        background:#E8F5E9;
        padding:25px;
        border-radius:18px;
        text-align:center;
    ">

        <h2>🎮 KobeitDos AI — Ойын</h2>

        <h3>
            Сұрақ {game2["q"]} / 5
        </h3>

        <h1 style="font-size:42px;">
            {game2["a"]} × {game2["b"]} = ?
        </h1>

        <p>
            Жауабыңды жазып, Enter бас.
        </p>

    </div>
    """

    game_input2.value = ""
    game_message2.value = ""


def game_check2(widget):

    if game_input2.value.strip() == "":
        return

    try:
        answer = int(game_input2.value)

    except:
        game_message2.value = """
        <h3 style="color:red;">
            ⚠️ Тек сан енгіз.
        </h3>
        """
        return


    if answer == game2["correct"]:

        game2["score"] += 1

    else:

        game2["mistakes"].append(
            f'{game2["a"]} × '
            f'{game2["b"]} = '
            f'{game2["correct"]}'
        )


    game2["q"] += 1

    game_question2()


game_input2.on_submit(game_check2)


game_box2 = widgets.VBox([
    game_html2,
    game_input2,
    game_message2
])


def game_start2():

    game2["q"] = 1
    game2["score"] = 0
    game2["mistakes"] = []

    game_input2.layout.display = ""

    game_question2()


# ==========================================================
# 🧠 ДИАГНОСТИКА
# ==========================================================

diag2 = {
    "questions": [],
    "index": 0,
    "results": {}
}


diag_html2 = widgets.HTML()

diag_input2 = widgets.Text(
    description="✏️ Жауап:",
    placeholder="Жауабыңды жазып, Enter бас...",
    layout=widgets.Layout(width="450px")
)

diag_message2 = widgets.HTML()


# Бұл нәтижелер кейін жеке жаттығуға керек
diagnostic_percent2 = {}

weakest_number2 = None


def diagnostic_start2():

    global diagnostic_percent2
    global weakest_number2

    diagnostic_percent2 = {}
    weakest_number2 = None

    diag2["questions"] = []
    diag2["index"] = 0

    diag2["results"] = {
        n: {
            "correct": 0,
            "total": 0
        }
        for n in range(2, 10)
    }


    # Әр кестеден 2 есеп
    for n in range(2, 10):

        for i in range(2):

            b = random.randint(2, 9)

            diag2["questions"].append(
                (n, b)
            )


    # Сұрақтарды араластыру
    random.shuffle(
        diag2["questions"]
    )

    diag_input2.layout.display = ""

    diagnostic_question2()


def diagnostic_question2():

    if diag2["index"] >= len(
        diag2["questions"]
    ):

        diagnostic_finish2()
        return


    a, b = diag2["questions"][
        diag2["index"]
    ]


    diag_html2.value = f"""
    <div style="
        background:#FFF3E0;
        padding:25px;
        border-radius:18px;
        text-align:center;
    ">

        <h2>
            🧠 KobeitDos AI — Диагностика
        </h2>

        <h3>
            Сұрақ {diag2["index"] + 1} / 16
        </h3>

        <h1 style="font-size:42px;">
            {a} × {b} = ?
        </h1>

        <p>
            Жауабыңды жазып, Enter бас.
        </p>

    </div>
    """

    diag_input2.value = ""
    diag_message2.value = ""


def diagnostic_check2(widget):

    if diag_input2.value.strip() == "":
        return


    try:
        answer = int(
            diag_input2.value
        )

    except:

        diag_message2.value = """
        <h3 style="color:red;">
            ⚠️ Тек сан енгіз.
        </h3>
        """

        return


    a, b = diag2["questions"][
        diag2["index"]
    ]

    correct_answer = a * b


    diag2["results"][a]["total"] += 1


    if answer == correct_answer:

        diag2["results"][a]["correct"] += 1


    diag2["index"] += 1

    diagnostic_question2()


diag_input2.on_submit(
    diagnostic_check2
)


def diagnostic_finish2():

    global diagnostic_percent2
    global weakest_number2


    diagnostic_percent2 = {}


    for n in range(2, 10):

        correct = (
            diag2["results"][n]["correct"]
        )

        total = (
            diag2["results"][n]["total"]
        )

        if total > 0:

            percent = int(
                correct / total * 100
            )

        else:

            percent = 0


        diagnostic_percent2[n] = percent


    # Ең төмен нәтиже көрсеткен кесте
    weakest_number2 = min(
        diagnostic_percent2,
        key=diagnostic_percent2.get
    )


    rows = ""


    for n in range(2, 10):

        p = diagnostic_percent2[n]

        if p == 100:
            icon = "🌟"
        elif p >= 50:
            icon = "👍"
        else:
            icon = "📚"


        rows += f"""
        <div style="
            background:white;
            margin:6px;
            padding:10px;
            border-radius:10px;
            font-size:18px;
        ">
            {icon}
            {n}-ге көбейту:
            <b>{p}%</b>
        </div>
        """


    diag_html2.value = f"""
    <div style="
        background:#FFF8E1;
        padding:25px;
        border-radius:18px;
        text-align:center;
    ">

        <h1>
            📊 Диагностика аяқталды!
        </h1>

        {rows}

        <br>

        <div style="
            background:#FFE0B2;
            padding:15px;
            border-radius:15px;
        ">

            <h2>🤖 KobeitDos AI анықтады</h2>

            <h2>
                Саған
                <span style="color:#d32f2f;">
                    {weakest_number2}-ге көбейтуді
                </span>
                көбірек жаттықтыру керек.
            </h2>

        </div>

    </div>
    """


    diag_input2.layout.display = "none"
    diag_message2.value = ""


diag_box2 = widgets.VBox([
    diag_html2,
    diag_input2,
    diag_message2
])


# ==========================================================
# 3. МӘЗІРДІ БАСҚАРУ
# ==========================================================

def app_change(change):

    section = change["new"]


    # Барлық бөлімді жасыру
    home_box.layout.display = "none"
    learn_box2.layout.display = "none"
    game_box2.layout.display = "none"
    diag_box2.layout.display = "none"


    # 🏠 Басты бет
    if section == "home":

        home_box.layout.display = ""


    # 📚 Үйрену
    elif section == "learn":

        learn_box2.layout.display = ""


    # 🎮 Ойын
    elif section == "game":

        game_box2.layout.display = ""

        game_start2()


    # 🧠 Диагностика
    elif section == "diagnostic":

        diag_box2.layout.display = ""

        diagnostic_start2()


app_menu.observe(
    app_change,
    names="value"
)


# ==========================================================
# 4. БАРЛЫҒЫН БІР ПЛАТФОРМАҒА ЖИНАУ
# ==========================================================

KobeitDos_AI = widgets.VBox([
    app_title,
    app_menu,
    home_box,
    learn_box2,
    game_box2,
    diag_box2
])


display(KobeitDos_AI)


# Алғашқы көрініс
home_box.layout.display = ""
learn_box2.layout.display = "none"
game_box2.layout.display = "none"
diag_box2.layout.display = "none"

VBox(children=(HTML(value='\n<div style="\n    background:linear-gradient(135deg,#667eea,#42a5f5);\n    paddin…

✅ Жаңа оқушыға дайын!
💾 Бұрынғы оқушының Excel-дегі нәтижесі сақтаулы.
✅ Жаңа оқушыға дайын!
💾 Бұрынғы оқушының Excel-дегі нәтижесі сақтаулы.

In [ ]:
# ==========================================================
# 🎯 KobeitDos AI — ЖЕКЕ ЖАТТЫҒУ
# Диагностикадағы әлсіз кестеге автоматты тапсырма береді
# ==========================================================

practice3 = {
    "q": 1,
    "score": 0,
    "number": None,
    "b": 0,
    "correct": 0,
    "mistakes": []
}

practice_percent3 = 0


# Экран
practice_html3 = widgets.HTML()

practice_input3 = widgets.Text(
    description="✏️ Жауап:",
    placeholder="Жауабыңды жазып, Enter бас...",
    layout=widgets.Layout(width="450px")
)

practice_message3 = widgets.HTML()


# ----------------------------------------------------------
# Жеке жаттығуды бастау
# ----------------------------------------------------------

def practice_start3():

    global practice_percent3

    # Диагностика әлі аяқталмаған болса
    if weakest_number2 is None:

        practice_html3.value = """
        <div style="
            background:#FFF3E0;
            padding:25px;
            border-radius:18px;
            text-align:center;
        ">
            <h2>⚠️ Алдымен диагностикадан өт!</h2>

            <p style="font-size:18px;">
                KobeitDos AI қай кестеден қиналғаныңды
                анықтауы керек.
            </p>

            <p>
                📌 Мәзірден «🧠 Диагностика» бөлімін таңда.
            </p>
        </div>
        """

        practice_input3.layout.display = "none"
        return


    # Диагностика аяқталған болса
    practice3["q"] = 1
    practice3["score"] = 0
    practice3["number"] = weakest_number2
    practice3["mistakes"] = []

    practice_percent3 = 0

    practice_input3.layout.display = ""

    practice_question3()


# ----------------------------------------------------------
# Жаңа сұрақ
# ----------------------------------------------------------

def practice_question3():

    if practice3["q"] > 5:

        practice_finish3()
        return


    practice3["b"] = random.randint(2, 9)

    practice3["correct"] = (
        practice3["number"] *
        practice3["b"]
    )


    practice_html3.value = f"""
    <div style="
        background:#F3E5F5;
        padding:25px;
        border-radius:18px;
        text-align:center;
    ">

        <h2>🎯 Жеке жаттығу</h2>

        <p style="font-size:18px;">
            🤖 Диагностика бойынша саған
            <b>{practice3["number"]}-ге көбейтуді</b>
            жаттықтыру ұсынылды.
        </p>

        <h3>
            Сұрақ {practice3["q"]} / 5
        </h3>

        <h1 style="font-size:42px;">
            {practice3["number"]} ×
            {practice3["b"]} = ?
        </h1>

        <p>
            Жауабыңды жазып, Enter бас.
        </p>

    </div>
    """

    practice_input3.value = ""
    practice_message3.value = ""


# ----------------------------------------------------------
# Жауапты тексеру
# ----------------------------------------------------------

def practice_check3(widget):

    if practice_input3.value.strip() == "":
        return

    try:

        answer = int(
            practice_input3.value
        )

    except:

        practice_message3.value = """
        <h3 style="color:red;">
            ⚠️ Тек сан енгіз.
        </h3>
        """

        return


    if answer == practice3["correct"]:

        practice3["score"] += 1

    else:

        practice3["mistakes"].append(
            f'{practice3["number"]} × '
            f'{practice3["b"]} = '
            f'{practice3["correct"]}'
        )


    practice3["q"] += 1

    practice_question3()


practice_input3.on_submit(
    practice_check3
)


# ----------------------------------------------------------
# Жаттығу қорытындысы
# ----------------------------------------------------------

def practice_finish3():

    global practice_percent3

    practice_percent3 = (
        practice3["score"] * 20
    )

    before = diagnostic_percent2[
        practice3["number"]
    ]

    after = practice_percent3

    difference = after - before


    if difference > 0:

        result_text = f"""
        🌟 Нәтижең <b>{difference}%</b> жақсарды!
        """

    elif difference == 0:

        result_text = """
        👍 Нәтижең тұрақты.
        Тағы жаттығып көр.
        """

    else:

        result_text = """
        📚 Бұл кестені тағы қайталау пайдалы болады.
        """


    if len(practice3["mistakes"]) == 0:

        mistakes_html = """
        <h3 style="color:green;">
            🌟 Барлық есеп дұрыс!
        </h3>
        """

    else:

        mistake_list = "<br>".join(
            practice3["mistakes"]
        )

        mistakes_html = f"""
        <div style="
            background:white;
            padding:12px;
            border-radius:12px;
        ">
            <b>📌 Қайталау керек есептер:</b>
            <br>
            {mistake_list}
        </div>
        """


    practice_html3.value = f"""
    <div style="
        background:#E8F5E9;
        padding:25px;
        border-radius:18px;
        text-align:center;
    ">

        <h1>🎉 Жеке жаттығу аяқталды!</h1>

        <h2>
            {practice3["number"]}-ге көбейту
        </h2>

        <p style="font-size:20px;">
            🧠 Диагностика нәтижесі:
            <b>{before}%</b>
        </p>

        <p style="font-size:20px;">
            🎯 Жаттығудан кейін:
            <b>{after}%</b>
        </p>

        <h2>
            {result_text}
        </h2>

        {mistakes_html}

    </div>
    """

    practice_input3.layout.display = "none"
    practice_message3.value = ""


# Жеке жаттығу блогы
practice_box3 = widgets.VBox([
    practice_html3,
    practice_input3,
    practice_message3
])


# ==========================================================
# ЖЕКЕ ЖАТТЫҒУДЫ ПЛАТФОРМАҒА ҚОСУ
# ==========================================================

# Мәзірге жаңа бөлім қосамыз
app_menu.options = [
    ("🏠 Басты бет", "home"),
    ("📚 Үйрену", "learn"),
    ("🎮 Ойын", "game"),
    ("🧠 Диагностика", "diagnostic"),
    ("🎯 Жеке жаттығу", "practice")
]


# Жаңа блокты платформаның ішіне қосамыз
KobeitDos_AI.children = (
    app_title,
    app_menu,
    home_box,
    learn_box2,
    game_box2,
    diag_box2,
    practice_box3
)


# Алдымен жасырамыз
practice_box3.layout.display = "none"


# ==========================================================
# МӘЗІР ФУНКЦИЯСЫН ЖАҢАРТУ
# ==========================================================

app_menu.unobserve(
    app_change,
    names="value"
)


def app_change3(change):

    section = change["new"]


    # Барлық бөлімді жасырамыз
    home_box.layout.display = "none"
    learn_box2.layout.display = "none"
    game_box2.layout.display = "none"
    diag_box2.layout.display = "none"
    practice_box3.layout.display = "none"


    if section == "home":

        home_box.layout.display = ""


    elif section == "learn":

        learn_box2.layout.display = ""


    elif section == "game":

        game_box2.layout.display = ""
        game_start2()


    elif section == "diagnostic":

        diag_box2.layout.display = ""
        diagnostic_start2()


    elif section == "practice":

        practice_box3.layout.display = ""
        practice_start3()


app_menu.observe(
    app_change3,
    names="value"
)

In [ ]:
# ==========================================================
# 📊 KobeitDos AI — МЕНІҢ НӘТИЖЕМ
# ==========================================================

result_box4 = widgets.HTML()


def show_result4():

    # Диагностика аяқталмаған болса
    if weakest_number2 is None:

        result_box4.value = """
        <div style="
            background:#FFF3E0;
            padding:25px;
            border-radius:18px;
            text-align:center;
        ">
            <h2>⚠️ Нәтиже әлі дайын емес</h2>
            <p>
                Алдымен 🧠 Диагностикадан өт.
            </p>
        </div>
        """
        return


    # Диагностика нәтижелері
    rows = ""

    for n in range(2, 10):

        p = diagnostic_percent2[n]

        if p == 100:
            status = "🌟 Өте жақсы"

        elif p >= 50:
            status = "👍 Жақсы"

        else:
            status = "📚 Жаттығу керек"


        rows += f"""
        <tr>
            <td style="
                padding:10px;
                border:1px solid #ddd;
            ">
                {n}-ге көбейту
            </td>

            <td style="
                padding:10px;
                border:1px solid #ddd;
            ">
                <b>{p}%</b>
            </td>

            <td style="
                padding:10px;
                border:1px solid #ddd;
            ">
                {status}
            </td>
        </tr>
        """


    # Жеке жаттығу орындалды ма?
    if practice3["number"] is not None and practice3["q"] > 5:

        before = diagnostic_percent2[
            weakest_number2
        ]

        after = practice_percent3

        difference = after - before


        if difference > 0:

            change_text = f"""
            🌟 Нәтижең
            <b>{difference}%</b>
            жақсарды!
            """

        elif difference == 0:

            change_text = """
            👍 Нәтижең тұрақты.
            Тағы жаттығу жасап көр.
            """

        else:

            change_text = """
            📚 Бұл кестені тағы қайталау ұсынылады.
            """


        practice_result = f"""
        <div style="
            background:#E8F5E9;
            padding:20px;
            border-radius:15px;
            margin-top:15px;
            text-align:center;
        ">

            <h2>🎯 Жеке жаттығу нәтижесі</h2>

            <p style="font-size:19px;">
                Диагностика:
                <b>{before}%</b>
            </p>

            <p style="font-size:19px;">
                Жаттығудан кейін:
                <b>{after}%</b>
            </p>

            <h3>
                {change_text}
            </h3>

        </div>
        """

    else:

        practice_result = """
        <div style="
            background:#F3E5F5;
            padding:20px;
            border-radius:15px;
            margin-top:15px;
            text-align:center;
        ">

            <h3>
                🎯 Жеке жаттығу әлі аяқталмаған.
            </h3>

        </div>
        """


    # Толық нәтиже
    result_box4.value = f"""
    <div style="
        background:#F7F8FF;
        padding:25px;
        border-radius:20px;
    ">

        <h1 style="text-align:center;">
            📊 Менің нәтижем
        </h1>

        <h2 style="text-align:center;">
            🧠 Диагностика
        </h2>

        <table style="
            width:100%;
            border-collapse:collapse;
            background:white;
            text-align:center;
        ">

            <tr style="background:#E8EEFF;">

                <th style="
                    padding:10px;
                    border:1px solid #ddd;
                ">
                    Кесте
                </th>

                <th style="
                    padding:10px;
                    border:1px solid #ddd;
                ">
                    Нәтиже
                </th>

                <th style="
                    padding:10px;
                    border:1px solid #ddd;
                ">
                    Қорытынды
                </th>

            </tr>

            {rows}

        </table>


        <div style="
            background:#FFF3E0;
            padding:20px;
            border-radius:15px;
            margin-top:15px;
            text-align:center;
        ">

            <h2>🤖 KobeitDos AI ұсынысы</h2>

            <p style="font-size:20px;">
                Көбірек жаттығуды қажет ететін кесте:
            </p>

            <h2 style="color:#d32f2f;">
                {weakest_number2}-ге көбейту
            </h2>

        </div>

        {practice_result}

    </div>
    """


# ==========================================================
# 📊 НӘТИЖЕНІ МӘЗІРГЕ ҚОСУ
# ==========================================================

app_menu.options = [
    ("🏠 Басты бет", "home"),
    ("📚 Үйрену", "learn"),
    ("🎮 Ойын", "game"),
    ("🧠 Диагностика", "diagnostic"),
    ("🎯 Жеке жаттығу", "practice"),
    ("📊 Менің нәтижем", "result")
]


# Платформаға нәтижені қосу
KobeitDos_AI.children = (
    app_title,
    app_menu,
    home_box,
    learn_box2,
    game_box2,
    diag_box2,
    practice_box3,
    result_box4
)

result_box4.layout.display = "none"


# Алдыңғы мәзір байланысын алып тастау
app_menu.unobserve(
    app_change3,
    names="value"
)


# ==========================================================
# ЖАҢА ТОЛЫҚ МӘЗІР
# ==========================================================

def app_change4(change):

    section = change["new"]


    # Барлығын жасыру
    home_box.layout.display = "none"
    learn_box2.layout.display = "none"
    game_box2.layout.display = "none"
    diag_box2.layout.display = "none"
    practice_box3.layout.display = "none"
    result_box4.layout.display = "none"


    if section == "home":

        home_box.layout.display = ""


    elif section == "learn":

        learn_box2.layout.display = ""


    elif section == "game":

        game_box2.layout.display = ""
        game_start2()


    elif section == "diagnostic":

        diag_box2.layout.display = ""
        diagnostic_start2()


    elif section == "practice":

        practice_box3.layout.display = ""
        practice_start3()


    elif section == "result":

        result_box4.layout.display = ""
        show_result4()


app_menu.observe(
    app_change4,
    names="value"
)

In [ ]:
# ==========================================================
# 👤 KobeitDos AI — ОҚУШЫНЫҢ АТЫ
# ==========================================================

# Оқушы аты сақталатын айнымалы
student_name5 = ""

# Аты-жөнін енгізу
student_input5 = widgets.Text(
    description="👤 Оқушы:",
    placeholder="Аты-жөніңді жаз...",
    layout=widgets.Layout(width="450px")
)

# Оқушыға хабарлама
student_hello5 = widgets.HTML(
    value="""
    <div style="
        background:#F4F6FF;
        padding:12px;
        border-radius:12px;
    ">
        👆 Алдымен аты-жөніңді жаз.
    </div>
    """
)


# Enter басылғанда оқушы атын сақтау
def save_student5(widget):

    global student_name5

    name = student_input5.value.strip()

    if name == "":

        student_hello5.value = """
        <div style="
            background:#FFEBEE;
            padding:12px;
            border-radius:12px;
        ">
            ⚠️ Аты-жөніңді жаз.
        </div>
        """

        return

    student_name5 = name

    student_hello5.value = f"""
    <div style="
        background:#E8F5E9;
        padding:15px;
        border-radius:12px;
        text-align:center;
    ">
        <h3>
            👋 Қош келдің, {student_name5}!
        </h3>

        <p>
            📌 Енді мәзірден қажетті бөлімді таңда.
        </p>
    </div>
    """


student_input5.on_submit(save_student5)


# Аты-жөнін бір блокқа жинау
student_box5 = widgets.VBox([
    student_input5,
    student_hello5
])


# ==========================================================
# ОҚУШЫ БЛОГЫН ПЛАТФОРМАҒА ҚОСУ
# ==========================================================

KobeitDos_AI.children = (
    app_title,
    student_box5,
    app_menu,
    home_box,
    learn_box2,
    game_box2,
    diag_box2,
    practice_box3,
    result_box4
)

In [ ]:
# ==========================================================
# 📊 KobeitDos AI — НӘТИЖЕ + ДИАГРАММА
# ==========================================================

def show_result5():

    # Оқушы аты
    if student_name5.strip() == "":
        name_text = "Оқушы"
    else:
        name_text = student_name5


    # Диагностика әлі аяқталмаған болса
    if weakest_number2 is None:

        result_box4.value = f"""
        <div style="
            background:#FFF3E0;
            padding:25px;
            border-radius:18px;
            text-align:center;
        ">
            <h2>👤 {name_text}</h2>

            <h2>⚠️ Нәтиже әлі дайын емес</h2>

            <p>
                Алдымен 🧠 Диагностикадан өт.
            </p>
        </div>
        """

        return


    # ------------------------------------------------------
    # 2–9 кестелерінің нәтижесі
    # ------------------------------------------------------

    result_cards = ""

    for n in range(2, 10):

        p = diagnostic_percent2[n]

        if p == 100:
            status = "🌟 Өте жақсы"

        elif p >= 50:
            status = "👍 Жақсы"

        else:
            status = "📚 Жаттығу керек"


        result_cards += f"""
        <div style="
            background:white;
            padding:12px;
            margin:7px 0;
            border-radius:12px;
            border:1px solid #ddd;
        ">

            <div style="
                display:flex;
                justify-content:space-between;
                font-size:17px;
                margin-bottom:7px;
            ">

                <b>{n}-ге көбейту</b>

                <span>
                    <b>{p}%</b> — {status}
                </span>

            </div>


            <div style="
                width:100%;
                height:22px;
                background:#E5E7EB;
                border-radius:11px;
                overflow:hidden;
            ">

                <div style="
                    width:{p}%;
                    height:22px;
                    background:linear-gradient(
                        90deg,
                        #667eea,
                        #42a5f5
                    );
                    border-radius:11px;
                ">
                </div>

            </div>

        </div>
        """


    # ------------------------------------------------------
    # Жеке жаттығу нәтижесі
    # ------------------------------------------------------

    if (
        practice3["number"] is not None
        and practice3["q"] > 5
    ):

        before = diagnostic_percent2[
            weakest_number2
        ]

        after = practice_percent3

        difference = after - before


        if difference > 0:

            change_text = f"""
            🌟 Нәтижең
            <b>{difference}%</b>
            жақсарды!
            """

        elif difference == 0:

            change_text = """
            👍 Нәтижең тұрақты.
            Жаттығуды жалғастыр.
            """

        else:

            change_text = """
            📚 Осы кестені тағы бір рет
            жаттықтыру ұсынылады.
            """


        practice_html = f"""
        <div style="
            background:#E8F5E9;
            padding:20px;
            border-radius:15px;
            margin-top:20px;
            text-align:center;
        ">

            <h2>🎯 Жеке жаттығудан кейін</h2>

            <h3>
                {weakest_number2}-ге көбейту
            </h3>

            <div style="
                display:flex;
                justify-content:center;
                gap:40px;
                flex-wrap:wrap;
            ">

                <div>
                    <h3>🧠 Бұрын</h3>
                    <h1>{before}%</h1>
                </div>

                <div style="
                    font-size:35px;
                    padding-top:35px;
                ">
                    ➜
                </div>

                <div>
                    <h3>🎯 Кейін</h3>
                    <h1>{after}%</h1>
                </div>

            </div>

            <h3>
                {change_text}
            </h3>

        </div>
        """

    else:

        practice_html = """
        <div style="
            background:#F3E5F5;
            padding:18px;
            border-radius:15px;
            margin-top:20px;
            text-align:center;
        ">
            <h3>
                🎯 Жеке жаттығу әлі аяқталмаған
            </h3>
        </div>
        """


    # ------------------------------------------------------
    # БАРЛЫҒЫН ШЫҒАРУ
    # ------------------------------------------------------

    result_box4.value = f"""
    <div style="
        background:#F7F8FF;
        padding:25px;
        border-radius:20px;
    ">

        <div style="
            text-align:center;
            background:#E8EEFF;
            padding:18px;
            border-radius:15px;
        ">

            <h1>📊 Менің нәтижем</h1>

            <h2>
                👤 {name_text}
            </h2>

        </div>


        <h2 style="text-align:center;">
            🧠 Диагностика нәтижелері
        </h2>


        {result_cards}


        <div style="
            background:#FFF3E0;
            padding:20px;
            border-radius:15px;
            margin-top:20px;
            text-align:center;
        ">

            <h2>🤖 KobeitDos AI ұсынысы</h2>

            <p style="font-size:18px;">
                Көбірек жаттығуды қажет ететін кесте:
            </p>

            <h1 style="color:#d32f2f;">
                {weakest_number2}-ге көбейту
            </h1>

        </div>


        {practice_html}

    </div>
    """


# ==========================================================
# МӘЗІРДЕГІ НӘТИЖЕ ФУНКЦИЯСЫН ЖАҢАРТУ
# ==========================================================

app_menu.unobserve(
    app_change4,
    names="value"
)


def app_change5(change):

    section = change["new"]


    # Барлық бөлімді жасырамыз
    home_box.layout.display = "none"
    learn_box2.layout.display = "none"
    game_box2.layout.display = "none"
    diag_box2.layout.display = "none"
    practice_box3.layout.display = "none"
    result_box4.layout.display = "none"


    if section == "home":

        home_box.layout.display = ""


    elif section == "learn":

        learn_box2.layout.display = ""


    elif section == "game":

        game_box2.layout.display = ""
        game_start2()


    elif section == "diagnostic":

        diag_box2.layout.display = ""
        diagnostic_start2()


    elif section == "practice":

        practice_box3.layout.display = ""
        practice_start3()


    elif section == "result":

        result_box4.layout.display = ""

        show_result5()


app_menu.observe(
    app_change5,
    names="value"
)

In [ ]:
# ==========================================================
# 💾 KobeitDos AI — ОҚУШЫ НӘТИЖЕЛЕРІН САҚТАУ
# ==========================================================

import pandas as pd

# Нәтижелер жиналатын тізім
student_results6 = []


def save_result6():

    # 1. Оқушының аты енгізілгенін тексеру
    if student_name5.strip() == "":
        print("⚠️ Алдымен оқушының аты-жөнін енгізіңіз.")
        return

    # 2. Диагностика орындалғанын тексеру
    if weakest_number2 is None:
        print("⚠️ Алдымен диагностикадан өтіңіз.")
        return

    # 3. Жеке жаттығу аяқталғанын тексеру
    if practice3["number"] is None or practice3["q"] <= 5:
        print("⚠️ Алдымен жеке жаттығуды толық аяқтаңыз.")
        return


    # Диагностикадағы нәтиже
    before = diagnostic_percent2[weakest_number2]

    # Жеке жаттығудан кейінгі нәтиже
    after = practice_percent3

    # Өзгеріс
    difference = after - before


    # Оқушы нәтижесі
    new_result = {
        "Оқушы": student_name5,
        "Әлсіз кесте": weakest_number2,
        "Диагностика (%)": before,
        "Жаттығудан кейін (%)": after,
        "Өзгеріс (%)": difference
    }


    # Кестеге қосу
    student_results6.append(new_result)


    # DataFrame жасау
    df_results6 = pd.DataFrame(student_results6)


    print("✅ Нәтиже сақталды!")
    print()

    display(df_results6)


# Қазіргі оқушының нәтижесін сақтау
save_result6()

✅ Нәтиже сақталды!

   Оқушы  Әлсіз кесте  Диагностика (%)  Жаттығудан кейін (%)  Өзгеріс (%)
0  Арнұр            5               50                    60           10

In [ ]:
# ==========================================================
# 💾 KobeitDos AI — НӘТИЖЕНІ GOOGLE DRIVE-ҚА EXCEL БОЛЫП САҚТАУ
# ==========================================================

from google.colab import drive
import pandas as pd
import os

# Google Drive-ты қосу
drive.mount('/content/drive')

# Excel файлының орны
file_path7 = "/content/drive/MyDrive/KobeitDos_AI_natizhe.xlsx"


def save_to_excel7():

    # Қазіргі оқушының нәтижесі
    before = diagnostic_percent2[weakest_number2]
    after = practice_percent3
    difference = after - before

    new_student = pd.DataFrame([{
        "Оқушы": student_name5,
        "Әлсіз кесте": weakest_number2,
        "Диагностика (%)": before,
        "Жаттығудан кейін (%)": after,
        "Өзгеріс (%)": difference
    }])

    # Егер Excel бұрыннан бар болса
    if os.path.exists(file_path7):

        old_data = pd.read_excel(file_path7)

        # Жаңа оқушыны қосу
        all_data = pd.concat(
            [old_data, new_student],
            ignore_index=True
        )

    else:

        # Бірінші оқушы болса
        all_data = new_student


    # Excel-ге сақтау
    all_data.to_excel(
        file_path7,
        index=False
    )

    print("✅ Нәтиже Google Drive-қа сақталды!")
    print()
    print("📁 Файл:")
    print("KobeitDos_AI_natizhe.xlsx")
    print()

    display(all_data)


# Сақтау
save_to_excel7()

Mounted at /content/drive
✅ Нәтиже Google Drive-қа сақталды!

📁 Файл:
KobeitDos_AI_natizhe.xlsx

   Оқушы  Әлсіз кесте  Диагностика (%)  Жаттығудан кейін (%)  Өзгеріс (%)
0  Арнұр            5               50                    60           10

In [ ]:
# ==========================================================
# 👥 KobeitDos AI — КЕЛЕСІ ОҚУШЫ
# ==========================================================

def next_student8():

    global student_name5
    global weakest_number2
    global diagnostic_percent2
    global practice_percent3

    # ------------------------------------------
    # 1. Оқушының атын тазалау
    # ------------------------------------------

    student_name5 = ""

    student_input5.value = ""

    student_hello5.value = """
    <div style="
        background:#E3F2FD;
        padding:15px;
        border-radius:12px;
        text-align:center;
    ">
        <h3>👤 Жаңа оқушы</h3>
        <p>
            Аты-жөніңді жазып,
            <b>Enter</b> бас.
        </p>
    </div>
    """


    # ------------------------------------------
    # 2. Диагностика нәтижесін тазалау
    # ------------------------------------------

    weakest_number2 = None
    diagnostic_percent2 = {}

    diag2["questions"] = []
    diag2["index"] = 0
    diag2["results"] = {}


    # ------------------------------------------
    # 3. Жеке жаттығуды тазалау
    # ------------------------------------------

    practice3["q"] = 1
    practice3["score"] = 0
    practice3["number"] = None
    practice3["b"] = 0
    practice3["correct"] = 0
    practice3["mistakes"] = []

    practice_percent3 = 0


    # ------------------------------------------
    # 4. Ойын нәтижесін де тазалау
    # ------------------------------------------

    game2["q"] = 1
    game2["score"] = 0
    game2["a"] = 0
    game2["b"] = 0
    game2["correct"] = 0
    game2["mistakes"] = []


    # ------------------------------------------
    # 5. Нәтиже бетін тазалау
    # ------------------------------------------

    result_box4.value = """
    <div style="
        background:#F4F6FF;
        padding:25px;
        border-radius:18px;
        text-align:center;
    ">
        <h2>👤 Жаңа оқушы дайын</h2>

        <p style="font-size:18px;">
            Алдымен аты-жөніңді енгіз.
        </p>

        <p>
            Содан кейін 🧠 Диагностикадан өт.
        </p>
    </div>
    """


    # Басты бетке қайтару
    app_menu.value = "home"

    print("✅ Жаңа оқушыға дайын!")
    print("💾 Бұрынғы оқушының Excel-дегі нәтижесі сақтаулы.")


# ӘЗІРГЕ ФУНКЦИЯНЫ ҚОСПАЙМЫЗ
print("✅ «Келесі оқушы» жүйесі дайын.")

✅ «Келесі оқушы» жүйесі дайын.

In [ ]:
# ==========================================================
# 👥 KobeitDos AI — «КЕЛЕСІ ОҚУШЫ» БАТЫРМАСЫ
# ==========================================================

# Батырма
next_student_button9 = widgets.Button(
    description="👥 Келесі оқушы",
    button_style="info",
    tooltip="Жаңа оқушыға көшу",
    layout=widgets.Layout(
        width="220px",
        height="45px"
    )
)

# Хабарлама
next_student_message9 = widgets.HTML()


# Батырма басылғанда
def next_student_click9(b):

    # Жаңа оқушы режимін іске қосамыз
    next_student8()

    # Хабарлама
    next_student_message9.value = """
    <div style="
        background:#E8F5E9;
        padding:12px;
        margin-top:8px;
        border-radius:12px;
        text-align:center;
    ">
        ✅ Жаңа оқушыға дайын!
        <br>
        👤 Аты-жөнін енгізіп, <b>Enter</b> басыңыз.
    </div>
    """


# Батырманы функцияға байланыстыру
next_student_button9.on_click(next_student_click9)


# Батырма блогы
next_student_box9 = widgets.VBox([
    next_student_button9,
    next_student_message9
])


# ==========================================================
# БАТЫРМАНЫ ПЛАТФОРМАҒА ҚОСУ
# ==========================================================

KobeitDos_AI.children = (
    app_title,
    student_box5,
    next_student_box9,
    app_menu,
    home_box,
    learn_box2,
    game_box2,
    diag_box2,
    practice_box3,
    result_box4
)

print("✅ «Келесі оқушы» батырмасы платформаға қосылды.")

✅ «Келесі оқушы» батырмасы платформаға қосылды.

In [ ]:
# ==========================================================
# 💾 KobeitDos AI — «НӘТИЖЕНІ САҚТАУ» БАТЫРМАСЫ
# ==========================================================

import pandas as pd
import os

# Excel файлының жолы
file_path10 = "/content/drive/MyDrive/KobeitDos_AI_natizhe.xlsx"

# Осы оқушы сақталды ма?
saved_student10 = None


# ----------------------------------------------------------
# НӘТИЖЕНІ EXCEL-ГЕ САҚТАУ
# ----------------------------------------------------------

def save_student_excel10():

    global saved_student10

    # Аты енгізілді ме?
    if student_name5.strip() == "":
        return "⚠️ Алдымен оқушының аты-жөнін енгізіңіз."

    # Диагностика аяқталды ма?
    if weakest_number2 is None:
        return "⚠️ Алдымен диагностикадан өтіңіз."

    # Жеке жаттығу аяқталды ма?
    if practice3["number"] is None or practice3["q"] <= 5:
        return "⚠️ Алдымен жеке жаттығуды аяқтаңыз."

    # Осы оқушы осы сессияда сақталған болса
    if saved_student10 == student_name5:
        return f"⚠️ {student_name5} нәтижесі бұрын сақталған."


    before = diagnostic_percent2[weakest_number2]
    after = practice_percent3
    difference = after - before


    new_student = pd.DataFrame([{
        "Оқушы": student_name5,
        "Әлсіз кесте": weakest_number2,
        "Диагностика (%)": before,
        "Жаттығудан кейін (%)": after,
        "Өзгеріс (%)": difference
    }])


    # Бұрынғы Excel бар болса
    if os.path.exists(file_path10):

        old_data = pd.read_excel(file_path10)

        all_data = pd.concat(
            [old_data, new_student],
            ignore_index=True
        )

    else:

        all_data = new_student


    # Excel-ге сақтау
    all_data.to_excel(
        file_path10,
        index=False
    )

    saved_student10 = student_name5

    return (
        f"✅ {student_name5} нәтижесі сақталды! "
        f"📊 Жалпы оқушы саны: {len(all_data)}"
    )


# ----------------------------------------------------------
# БАТЫРМА
# ----------------------------------------------------------

save_button10 = widgets.Button(
    description="💾 Нәтижені сақтау",
    button_style="success",
    tooltip="Оқушы нәтижесін Excel-ге сақтау",
    layout=widgets.Layout(
        width="240px",
        height="45px"
    )
)

save_message10 = widgets.HTML()


def save_click10(b):

    message = save_student_excel10()

    save_message10.value = f"""
    <div style="
        background:#F1F8E9;
        padding:14px;
        margin-top:8px;
        border-radius:12px;
        text-align:center;
        font-size:16px;
    ">
        {message}
    </div>
    """


save_button10.on_click(save_click10)


save_box10 = widgets.VBox([
    save_button10,
    save_message10
])


# ----------------------------------------------------------
# ПЛАТФОРМАҒА ҚОСУ
# ----------------------------------------------------------

KobeitDos_AI.children = (
    app_title,
    student_box5,
    save_box10,
    next_student_box9,
    app_menu,
    home_box,
    learn_box2,
    game_box2,
    diag_box2,
    practice_box3,
    result_box4
)

print("✅ «Нәтижені сақтау» батырмасы қосылды.")

✅ «Нәтижені сақтау» батырмасы қосылды.

In [ ]:
# ==========================================================
# 🔄 KobeitDos AI — КЕЛЕСІ ОҚУШЫ ҮШІН САҚТАУДЫ ЖАҢАРТУ
# ==========================================================

def next_student_click11(b):

    global saved_student10

    # Алдыңғы оқушы сақталды деген белгіні тазалау
    saved_student10 = None

    # Жаңа оқушы режимі
    next_student8()

    # Сақтау хабарламасын тазалау
    save_message10.value = ""

    # Келесі оқушы хабарламасы
    next_student_message9.value = """
    <div style="
        background:#E8F5E9;
        padding:12px;
        margin-top:8px;
        border-radius:12px;
        text-align:center;
    ">
        ✅ Жаңа оқушыға дайын!
        <br>
        👤 Аты-жөніңді енгізіп,
        <b>Enter</b> бас.
        <br><br>
        🧠 Содан кейін диагностикадан өт.
    </div>
    """


# Ескі әрекетті батырмадан алып тастаймыз
next_student_button9.on_click(
    next_student_click9,
    remove=True
)

# Жаңа әрекетті қосамыз
next_student_button9.on_click(
    next_student_click11
)

print("✅ «Келесі оқушы» жүйесі жаңартылды.")

✅ «Келесі оқушы» жүйесі жаңартылды.

In [ ]:
# ==========================================================
# 📈 KobeitDos AI — СЫНЫП НӘТИЖЕСІ
# ==========================================================

import pandas as pd
import os

class_result12 = widgets.HTML()


def show_class_result12():

    # Excel файлы бар ма?
    if not os.path.exists(file_path10):

        class_result12.value = """
        <div style="
            background:#FFF3E0;
            padding:25px;
            border-radius:18px;
            text-align:center;
        ">
            <h2>📈 Сынып нәтижесі</h2>
            <p>⚠️ Әзірге сақталған нәтиже жоқ.</p>
        </div>
        """
        return


    # Excel файлын оқу
    df = pd.read_excel(file_path10)

    if len(df) == 0:

        class_result12.value = """
        <div style="
            background:#FFF3E0;
            padding:25px;
            border-radius:18px;
            text-align:center;
        ">
            <h2>📈 Сынып нәтижесі</h2>
            <p>⚠️ Әзірге оқушы нәтижесі жоқ.</p>
        </div>
        """
        return


    # ------------------------------------------------------
    # ЖАЛПЫ СТАТИСТИКА
    # ------------------------------------------------------

    student_count = len(df)

    avg_before = round(
        df["Диагностика (%)"].mean(), 1
    )

    avg_after = round(
        df["Жаттығудан кейін (%)"].mean(), 1
    )

    avg_change = round(
        df["Өзгеріс (%)"].mean(), 1
    )


    # Ең жиі кездескен әлсіз кесте
    weak_counts = df["Әлсіз кесте"].value_counts()

    most_difficult = int(
        weak_counts.index[0]
    )


    # Нәтижесі жақсарған оқушылар саны
    improved_count = int(
        (df["Өзгеріс (%)"] > 0).sum()
    )


    # ------------------------------------------------------
    # ОҚУШЫЛАР КЕСТЕСІ
    # ------------------------------------------------------

    student_rows = ""

    for _, row in df.iterrows():

        change = row["Өзгеріс (%)"]

        if change > 0:
            icon = "📈"

        elif change == 0:
            icon = "➖"

        else:
            icon = "📚"


        student_rows += f"""
        <tr>

            <td style="
                padding:9px;
                border:1px solid #ddd;
            ">
                {row["Оқушы"]}
            </td>

            <td style="
                padding:9px;
                border:1px solid #ddd;
                text-align:center;
            ">
                {int(row["Әлсіз кесте"])}
            </td>

            <td style="
                padding:9px;
                border:1px solid #ddd;
                text-align:center;
            ">
                {row["Диагностика (%)"]}%
            </td>

            <td style="
                padding:9px;
                border:1px solid #ddd;
                text-align:center;
            ">
                {row["Жаттығудан кейін (%)"]}%
            </td>

            <td style="
                padding:9px;
                border:1px solid #ddd;
                text-align:center;
            ">
                {icon} {change:+g}%
            </td>

        </tr>
        """


    # ------------------------------------------------------
    # HTML НӘТИЖЕ
    # ------------------------------------------------------

    class_result12.value = f"""
    <div style="
        background:#F7F8FF;
        padding:25px;
        border-radius:20px;
    ">

        <h1 style="text-align:center;">
            📈 Сынып нәтижесі
        </h1>

        <p style="
            text-align:center;
            color:#666;
        ">
            KobeitDos AI жалпы талдауы
        </p>


        <div style="
            display:flex;
            gap:12px;
            flex-wrap:wrap;
            justify-content:center;
            margin-top:20px;
        ">

            <div style="
                background:white;
                padding:18px;
                border-radius:15px;
                min-width:150px;
                text-align:center;
            ">
                <h3>👥 Оқушы саны</h3>
                <h1>{student_count}</h1>
            </div>


            <div style="
                background:white;
                padding:18px;
                border-radius:15px;
                min-width:170px;
                text-align:center;
            ">
                <h3>🧠 Бастапқы нәтиже</h3>
                <h1>{avg_before}%</h1>
            </div>


            <div style="
                background:white;
                padding:18px;
                border-radius:15px;
                min-width:170px;
                text-align:center;
            ">
                <h3>🎯 Кейінгі нәтиже</h3>
                <h1>{avg_after}%</h1>
            </div>


            <div style="
                background:#E8F5E9;
                padding:18px;
                border-radius:15px;
                min-width:160px;
                text-align:center;
            ">
                <h3>📊 Орташа өзгеріс</h3>
                <h1>{avg_change:+g}%</h1>
            </div>

        </div>


        <div style="
            background:#FFF3E0;
            padding:18px;
            border-radius:15px;
            text-align:center;
            margin-top:20px;
        ">

            <h2>🤖 KobeitDos AI талдауы</h2>

            <p style="font-size:18px;">
                Ең жиі қиындық туғызған кесте:
                <b>{most_difficult}-ге көбейту</b>
            </p>

            <p style="font-size:18px;">
                Нәтижесі жақсарған оқушылар:
                <b>{improved_count} / {student_count}</b>
            </p>

        </div>


        <h2 style="
            text-align:center;
            margin-top:25px;
        ">
            👥 Оқушылар нәтижесі
        </h2>


        <div style="overflow-x:auto;">

            <table style="
                width:100%;
                border-collapse:collapse;
                background:white;
            ">

                <tr style="
                    background:#E8EEFF;
                ">

                    <th style="padding:10px;">
                        Оқушы
                    </th>

                    <th style="padding:10px;">
                        Әлсіз кесте
                    </th>

                    <th style="padding:10px;">
                        Бастапқы
                    </th>

                    <th style="padding:10px;">
                        Кейін
                    </th>

                    <th style="padding:10px;">
                        Өзгеріс
                    </th>

                </tr>

                {student_rows}

            </table>

        </div>

    </div>
    """


# ==========================================================
# МӘЗІРГЕ «СЫНЫП НӘТИЖЕСІН» ҚОСУ
# ==========================================================

app_menu.options = [
    ("🏠 Басты бет", "home"),
    ("📚 Үйрену", "learn"),
    ("🎮 Ойын", "game"),
    ("🧠 Диагностика", "diagnostic"),
    ("🎯 Жеке жаттығу", "practice"),
    ("📊 Менің нәтижем", "result"),
    ("📈 Сынып нәтижесі", "class_result")
]


# Платформаға жаңа бөлімді қосу
KobeitDos_AI.children = (
    app_title,
    student_box5,
    save_box10,
    next_student_box9,
    app_menu,
    home_box,
    learn_box2,
    game_box2,
    diag_box2,
    practice_box3,
    result_box4,
    class_result12
)

class_result12.layout.display = "none"


# ==========================================================
# МӘЗІРДІ ЖАҢАРТУ
# ==========================================================

app_menu.unobserve(
    app_change5,
    names="value"
)


def app_change12(change):

    section = change["new"]

    # Барлық бөлімді жасыру
    home_box.layout.display = "none"
    learn_box2.layout.display = "none"
    game_box2.layout.display = "none"
    diag_box2.layout.display = "none"
    practice_box3.layout.display = "none"
    result_box4.layout.display = "none"
    class_result12.layout.display = "none"


    if section == "home":

        home_box.layout.display = ""


    elif section == "learn":

        learn_box2.layout.display = ""


    elif section == "game":

        game_box2.layout.display = ""
        game_start2()


    elif section == "diagnostic":

        diag_box2.layout.display = ""
        diagnostic_start2()


    elif section == "practice":

        practice_box3.layout.display = ""
        practice_start3()


    elif section == "result":

        result_box4.layout.display = ""
        show_result5()


    elif section == "class_result":

        class_result12.layout.display = ""

        # Excel-дегі ең соңғы деректерді қайта оқиды
        show_class_result12()


app_menu.observe(
    app_change12,
    names="value"
)

print("✅ «Сынып нәтижесі» бөлімі қосылды.")

✅ «Сынып нәтижесі» бөлімі қосылды.

In [ ]:
# ==========================================================
# 📊 KobeitDos AI — СЫНЫПТЫҢ САЛЫСТЫРМАЛЫ ДИАГРАММАСЫ
# ==========================================================

class_chart13 = widgets.HTML()


def show_class_chart13():

    # Excel файлы бар ма?
    if not os.path.exists(file_path10):

        class_chart13.value = """
        <div style="
            background:#FFF3E0;
            padding:20px;
            border-radius:15px;
            text-align:center;
        ">
            ⚠️ Диаграмма үшін нәтиже жоқ.
        </div>
        """
        return


    # Excel файлын оқу
    df = pd.read_excel(file_path10)

    if len(df) == 0:
        class_chart13.value = """
        <div style="
            background:#FFF3E0;
            padding:20px;
            border-radius:15px;
            text-align:center;
        ">
            ⚠️ Әзірге оқушы нәтижесі жоқ.
        </div>
        """
        return


    # Орташа нәтижелер
    before = round(
        df["Диагностика (%)"].mean(), 1
    )

    after = round(
        df["Жаттығудан кейін (%)"].mean(), 1
    )

    difference = round(
        after - before, 1
    )


    # Қорытынды мәтін
    if difference > 0:

        conclusion = f"""
        📈 Орташа нәтиже
        <b>{difference:g} пайыздық пунктке</b>
        жоғарылады.
        """

    elif difference == 0:

        conclusion = """
        ➖ Орташа нәтиже өзгерген жоқ.
        """

    else:

        conclusion = f"""
        📚 Орташа нәтиже
        <b>{abs(difference):g} пайыздық пунктке</b>
        төмендеді.
        """


    # Диаграмма
    class_chart13.value = f"""
    <div style="
        background:white;
        padding:25px;
        border-radius:20px;
        margin-top:20px;
        border:1px solid #E5E7EB;
    ">

        <h2 style="text-align:center;">
            📊 Бастапқы және кейінгі нәтиже
        </h2>

        <p style="
            text-align:center;
            color:#666;
        ">
            Сыныптың орташа көрсеткіші
        </p>


        <!-- БАСТАПҚЫ НӘТИЖЕ -->

        <div style="margin-top:25px;">

            <div style="
                display:flex;
                justify-content:space-between;
                font-size:18px;
            ">
                <b>🧠 Бастапқы нәтиже</b>
                <b>{before}%</b>
            </div>

            <div style="
                width:100%;
                height:35px;
                background:#E5E7EB;
                border-radius:18px;
                overflow:hidden;
                margin-top:8px;
            ">

                <div style="
                    width:{before}%;
                    height:35px;
                    background:#90CAF9;
                    border-radius:18px;
                ">
                </div>

            </div>

        </div>


        <!-- КЕЙІНГІ НӘТИЖЕ -->

        <div style="margin-top:25px;">

            <div style="
                display:flex;
                justify-content:space-between;
                font-size:18px;
            ">
                <b>🎯 Жаттығудан кейін</b>
                <b>{after}%</b>
            </div>

            <div style="
                width:100%;
                height:35px;
                background:#E5E7EB;
                border-radius:18px;
                overflow:hidden;
                margin-top:8px;
            ">

                <div style="
                    width:{after}%;
                    height:35px;
                    background:#81C784;
                    border-radius:18px;
                ">
                </div>

            </div>

        </div>


        <!-- ҚОРЫТЫНДЫ -->

        <div style="
            background:#E8F5E9;
            padding:18px;
            border-radius:15px;
            margin-top:25px;
            text-align:center;
            font-size:19px;
        ">

            <b>🤖 KobeitDos AI қорытындысы</b>

            <br><br>

            {conclusion}

        </div>

    </div>
    """


# ==========================================================
# ДИАГРАММАНЫ СЫНЫП НӘТИЖЕСІНЕ ҚОСУ
# ==========================================================

class_result_full13 = widgets.VBox([
    class_result12,
    class_chart13
])


# Платформаны жаңарту
KobeitDos_AI.children = (
    app_title,
    student_box5,
    save_box10,
    next_student_box9,
    app_menu,
    home_box,
    learn_box2,
    game_box2,
    diag_box2,
    practice_box3,
    result_box4,
    class_result_full13
)

class_result_full13.layout.display = "none"


# Алдыңғы мәзір байланысын алып тастау
app_menu.unobserve(
    app_change12,
    names="value"
)


# ==========================================================
# ЖАҢАРТЫЛҒАН МӘЗІР
# ==========================================================

def app_change13(change):

    section = change["new"]

    # Барлық бөлімді жасыру
    home_box.layout.display = "none"
    learn_box2.layout.display = "none"
    game_box2.layout.display = "none"
    diag_box2.layout.display = "none"
    practice_box3.layout.display = "none"
    result_box4.layout.display = "none"
    class_result_full13.layout.display = "none"


    if section == "home":

        home_box.layout.display = ""


    elif section == "learn":

        learn_box2.layout.display = ""


    elif section == "game":

        game_box2.layout.display = ""
        game_start2()


    elif section == "diagnostic":

        diag_box2.layout.display = ""
        diagnostic_start2()


    elif section == "practice":

        practice_box3.layout.display = ""
        practice_start3()


    elif section == "result":

        result_box4.layout.display = ""
        show_result5()


    elif section == "class_result":

        class_result_full13.layout.display = ""

        # Ең соңғы Excel нәтижесін оқу
        show_class_result12()
        show_class_chart13()


app_menu.observe(
    app_change13,
    names="value"
)

print("✅ Салыстырмалы диаграмма қосылды.")

✅ Салыстырмалы диаграмма қосылды.

In [ ]:
# ==========================================================
# 🎨 KobeitDos AI — БАСТЫ БЕТ ДИЗАЙНЫ
# ==========================================================

home_box.value = """
<div style="
    font-family:Arial, sans-serif;
    background:linear-gradient(135deg,#E3F2FD,#F3E5F5,#FFF8E1);
    padding:30px;
    border-radius:25px;
">

    <!-- ТАҚЫРЫП -->

    <div style="
        text-align:center;
        background:white;
        padding:25px;
        border-radius:22px;
        box-shadow:0 4px 12px rgba(0,0,0,0.08);
    ">

        <div style="font-size:55px;">
            ✖️ 🧠 🎯
        </div>

        <h1 style="
            font-size:36px;
            margin:8px;
            color:#3949AB;
        ">
            KobeitDos AI
        </h1>

        <h2 style="
            color:#555;
            font-weight:normal;
        ">
            Көбейту кестесін ақылды тәсілмен үйрен!
        </h2>

        <p style="
            font-size:18px;
            line-height:1.6;
        ">
            Бұл платформа сенің қай көбейту кестесінен
            қиналатыныңды анықтап,
            саған арнайы жаттығу ұсынады.
        </p>

    </div>


    <!-- МАҚСАТ -->

    <div style="
        background:#FFFDE7;
        padding:20px;
        border-radius:18px;
        margin-top:20px;
        text-align:center;
    ">

        <h2>🌟 Бүгінгі мақсат</h2>

        <p style="font-size:19px;">
            Көбейту кестесін
            <b>үйрену, тексеру және нәтижеңді жақсарту!</b>
        </p>

    </div>


    <!-- ҚАЛАЙ ЖҰМЫС ІСТЕЙДІ -->

    <h2 style="
        text-align:center;
        margin-top:28px;
        color:#3949AB;
    ">
        🚀 Қалай жұмыс істейді?
    </h2>


    <div style="
        display:flex;
        flex-wrap:wrap;
        gap:12px;
        justify-content:center;
    ">


        <div style="
            background:white;
            width:180px;
            padding:18px;
            border-radius:18px;
            text-align:center;
        ">

            <div style="font-size:38px;">📚</div>

            <h3>1. Үйрен</h3>

            <p>
                Көбейту кестесін
                қайталап үйрен.
            </p>

        </div>


        <div style="
            background:white;
            width:180px;
            padding:18px;
            border-radius:18px;
            text-align:center;
        ">

            <div style="font-size:38px;">🎮</div>

            <h3>2. Ойна</h3>

            <p>
                Ойын арқылы
                біліміңді тексер.
            </p>

        </div>


        <div style="
            background:white;
            width:180px;
            padding:18px;
            border-radius:18px;
            text-align:center;
        ">

            <div style="font-size:38px;">🧠</div>

            <h3>3. Диагностика</h3>

            <p>
                Қай кестеден
                қиналатыныңды анықта.
            </p>

        </div>


        <div style="
            background:white;
            width:180px;
            padding:18px;
            border-radius:18px;
            text-align:center;
        ">

            <div style="font-size:38px;">🎯</div>

            <h3>4. Жаттығу</h3>

            <p>
                Жүйе саған жеке
                тапсырма береді.
            </p>

        </div>


        <div style="
            background:white;
            width:180px;
            padding:18px;
            border-radius:18px;
            text-align:center;
        ">

            <div style="font-size:38px;">📊</div>

            <h3>5. Нәтиже</h3>

            <p>
                Өз жетістігіңді
                көр.
            </p>

        </div>

    </div>


    <!-- AI БӨЛІМІ -->

    <div style="
        background:#E8F5E9;
        padding:22px;
        border-radius:18px;
        margin-top:25px;
        text-align:center;
    ">

        <h2>🤖 KobeitDos AI қалай көмектеседі?</h2>

        <p style="
            font-size:18px;
            line-height:1.6;
        ">
            Диагностика нәтижесін талдап,
            қай көбейту кестесіне көбірек
            жаттығу қажет екенін анықтайды.
            Содан кейін сол кестеге арналған
            жеке тапсырмалар ұсынады.
        </p>

    </div>


    <!-- БАСТАУ -->

    <div style="
        background:#E8EAF6;
        padding:20px;
        border-radius:18px;
        margin-top:20px;
        text-align:center;
    ">

        <h2>🏆 Дайынсың ба?</h2>

        <p style="font-size:18px;">
            👤 Жоғарыға аты-жөніңді жазып,
            <b>Enter</b> бас.
        </p>

        <p style="font-size:18px;">
            Содан кейін 📌 мәзірден
            <b>📚 Үйрену</b> бөлімін таңда.
        </p>

    </div>

</div>
"""

print("✅ KobeitDos AI басты бетінің дизайны жаңартылды.")

✅ KobeitDos AI басты бетінің дизайны жаңартылды.

In [ ]:
# ==========================================================
# 🏠 KobeitDos AI — ЖАҢА БАСТЫ БЕТ
# ==========================================================

home_box14 = widgets.HTML(
    value="""
    <div style="
        font-family:Arial, sans-serif;
        background:#F5F7FF;
        padding:22px;
        border-radius:22px;
    ">

        <!-- 1. ТАҚЫРЫП -->
        <div style="
            text-align:center;
            background:linear-gradient(135deg,#667EEA,#42A5F5);
            padding:25px;
            border-radius:20px;
        ">

            <div style="font-size:42px;">
                🧠 ✖️ 🎯
            </div>

            <h1 style="
                margin:5px;
                color:white;
                font-size:34px;
            ">
                KobeitDos AI
            </h1>

            <p style="
                color:white;
                font-size:19px;
                margin:8px;
            ">
                Көбейту кестесін ақылды түрде үйрен!
            </p>

        </div>


        <!-- 2. БҮГІНГІ МАҚСАТ -->
        <div style="
            background:#FFF8E1;
            padding:16px;
            margin-top:15px;
            border-radius:16px;
            text-align:center;
        ">

            <h2 style="margin:5px;">
                🌟 Бүгінгі мақсат
            </h2>

            <p style="font-size:17px;">
                Көбейту кестесін үйрен,
                біліміңді тексер және
                нәтижеңді жақсарт!
            </p>

        </div>


        <!-- 3. ҚАЛАЙ ЖҰМЫС ІСТЕЙДІ -->
        <h2 style="
            text-align:center;
            color:#3949AB;
            margin-top:22px;
        ">
            🚀 Қалай жұмыс істейді?
        </h2>


        <div style="
            display:grid;
            grid-template-columns:
            repeat(auto-fit,minmax(140px,1fr));
            gap:10px;
        ">


            <div style="
                background:white;
                padding:14px;
                border-radius:15px;
                text-align:center;
            ">
                <div style="font-size:32px;">📚</div>
                <b>1. Үйрен</b>
                <p>Көбейту кестесін қайтала.</p>
            </div>


            <div style="
                background:white;
                padding:14px;
                border-radius:15px;
                text-align:center;
            ">
                <div style="font-size:32px;">🎮</div>
                <b>2. Ойна</b>
                <p>Ойын арқылы өзіңді тексер.</p>
            </div>


            <div style="
                background:white;
                padding:14px;
                border-radius:15px;
                text-align:center;
            ">
                <div style="font-size:32px;">🧠</div>
                <b>3. Диагностика</b>
                <p>Қай кесте қиын екенін анықта.</p>
            </div>


            <div style="
                background:white;
                padding:14px;
                border-radius:15px;
                text-align:center;
            ">
                <div style="font-size:32px;">🎯</div>
                <b>4. Жаттығу</b>
                <p>Жеке тапсырмаларды орында.</p>
            </div>


            <div style="
                background:white;
                padding:14px;
                border-radius:15px;
                text-align:center;
            ">
                <div style="font-size:32px;">📊</div>
                <b>5. Нәтиже</b>
                <p>Өз жетістігіңді бақыла.</p>
            </div>

        </div>


        <!-- 4. AI КӨМЕК -->
        <div style="
            background:#E8F5E9;
            padding:17px;
            margin-top:18px;
            border-radius:16px;
            text-align:center;
        ">

            <h2 style="margin:5px;">
                🤖 KobeitDos AI қалай көмектеседі?
            </h2>

            <p style="
                font-size:17px;
                line-height:1.5;
            ">
                Диагностика жауаптарын талдап,
                саған қай көбейту кестесін
                көбірек жаттықтыру керегін анықтайды.
                Содан кейін сол кестеге арналған
                жеке тапсырмалар береді.
            </p>

        </div>


        <!-- 5. БАСТАУ -->
        <div style="
            background:#E8EAF6;
            padding:16px;
            margin-top:15px;
            border-radius:16px;
            text-align:center;
        ">

            <h2 style="margin:5px;">
                🏆 Бастауға дайынсың ба?
            </h2>

            <p style="font-size:17px;">
                👤 Аты-жөніңді енгізіп,
                <b>Enter</b> бас.
                Содан кейін
                <b>📚 Үйрену</b> бөлімінен баста!
            </p>

        </div>

    </div>
    """
)


# ==========================================================
# ПЛАТФОРМАҒА ЖАҢА БАСТЫ БЕТТІ ҚОСУ
# ==========================================================

KobeitDos_AI.children = (
    app_title,
    student_box5,
    save_box10,
    next_student_box9,
    app_menu,
    home_box14,
    learn_box2,
    game_box2,
    diag_box2,
    practice_box3,
    result_box4,
    class_result_full13
)

home_box14.layout.display = "none"


# ==========================================================
# ЕСКІ МӘЗІР БАЙЛАНЫСЫН АЛЫП ТАСТАУ
# ==========================================================

app_menu.unobserve(
    app_change13,
    names="value"
)


# ==========================================================
# ЖАҢА МӘЗІР
# ==========================================================

def app_change14(change):

    section = change["new"]

    # Барлығын жасыру
    home_box14.layout.display = "none"
    learn_box2.layout.display = "none"
    game_box2.layout.display = "none"
    diag_box2.layout.display = "none"
    practice_box3.layout.display = "none"
    result_box4.layout.display = "none"
    class_result_full13.layout.display = "none"


    if section == "home":

        home_box14.layout.display = ""


    elif section == "learn":

        learn_box2.layout.display = ""


    elif section == "game":

        game_box2.layout.display = ""
        game_start2()


    elif section == "diagnostic":

        diag_box2.layout.display = ""
        diagnostic_start2()


    elif section == "practice":

        practice_box3.layout.display = ""
        practice_start3()


    elif section == "result":

        result_box4.layout.display = ""
        show_result5()


    elif section == "class_result":

        class_result_full13.layout.display = ""
        show_class_result12()
        show_class_chart13()


app_menu.observe(
    app_change14,
    names="value"
)


# Егер қазір басты бет таңдалып тұрса,
# жаңа бетті бірден көрсету
if app_menu.value == "home":
    home_box14.layout.display = ""


print("✅ Жаңа басты бет платформаға қосылды.")

✅ Жаңа басты бет платформаға қосылды.

In [ ]:
# ==========================================================
# 🎨 KobeitDos AI — БАТЫРМАЛАРДЫ ДҰРЫС ОРНАЛАСТЫРУ
# ==========================================================

# Нәтиже беті + басқару батырмалары
result_full15 = widgets.VBox([
    result_box4,
    save_box10,
    next_student_box9
])

# Бастапқыда жасырамыз
result_full15.layout.display = "none"


# ==========================================================
# ПЛАТФОРМАНЫ ҚАЙТА РЕТТЕУ
# ==========================================================

KobeitDos_AI.children = (
    app_title,
    student_box5,
    app_menu,
    home_box14,
    learn_box2,
    game_box2,
    diag_box2,
    practice_box3,
    result_full15,
    class_result_full13
)


# ==========================================================
# АЛДЫҢҒЫ МӘЗІР БАЙЛАНЫСЫН АЛЫП ТАСТАУ
# ==========================================================

app_menu.unobserve(
    app_change14,
    names="value"
)


# ==========================================================
# ЖАҢА МӘЗІР БАСҚАРУЫ
# ==========================================================

def app_change15(change):

    section = change["new"]

    # Барлық бөлімдерді жасыру
    home_box14.layout.display = "none"
    learn_box2.layout.display = "none"
    game_box2.layout.display = "none"
    diag_box2.layout.display = "none"
    practice_box3.layout.display = "none"
    result_full15.layout.display = "none"
    class_result_full13.layout.display = "none"


    # 🏠 БАСТЫ БЕТ
    if section == "home":

        home_box14.layout.display = ""


    # 📚 ҮЙРЕНУ
    elif section == "learn":

        learn_box2.layout.display = ""


    # 🎮 ОЙЫН
    elif section == "game":

        game_box2.layout.display = ""
        game_start2()


    # 🧠 ДИАГНОСТИКА
    elif section == "diagnostic":

        diag_box2.layout.display = ""
        diagnostic_start2()


    # 🎯 ЖЕКЕ ЖАТТЫҒУ
    elif section == "practice":

        practice_box3.layout.display = ""
        practice_start3()


    # 📊 МЕНІҢ НӘТИЖЕМ
    elif section == "result":

        result_full15.layout.display = ""

        # Нәтижені жаңарту
        show_result5()


    # 📈 СЫНЫП НӘТИЖЕСІ
    elif section == "class_result":

        class_result_full13.layout.display = ""

        show_class_result12()
        show_class_chart13()


# Жаңа мәзірді қосу
app_menu.observe(
    app_change15,
    names="value"
)


# Қазіргі таңдалған бөлімді дұрыс көрсету
current_section15 = app_menu.value

app_change15({
    "new": current_section15
})


print("✅ Батырмалар өз орындарына орналастырылды.")

✅ Батырмалар өз орындарына орналастырылды.

In [ ]:
# ==========================================================
# 👥 KobeitDos AI — «КЕЛЕСІ ОҚУШЫ» СОҢҒЫ НҰСҚА
# ==========================================================

def next_student_click16(b):

    global saved_student10

    # 1. Сақтау белгісін тазалау
    saved_student10 = None

    # 2. Бұрын жасаған жаңа оқушы функциясын іске қосу
    next_student8()

    # 3. Сақтау хабарламасын тазалау
    save_message10.value = ""

    # 4. «Келесі оқушы» хабарламасын да тазалау
    next_student_message9.value = ""

    # 5. Нәтиже бетін бастапқы күйге келтіру
    result_box4.value = """
    <div style="
        background:#F4F6FF;
        padding:25px;
        border-radius:18px;
        text-align:center;
    ">
        <h2>👤 Жаңа оқушы</h2>

        <p style="font-size:18px;">
            Алдымен аты-жөніңді енгіз.
        </p>

        <p>
            Содан кейін 🧠 Диагностикадан өт.
        </p>
    </div>
    """

    # 6. Автоматты түрде басты бетке өту
    app_menu.value = "home"

    # 7. Аты-жөні жазылатын жолға курсор қоюға тырысамыз
    try:
        student_input5.focus()
    except:
        pass


# ==========================================================
# БҰРЫНҒЫ БАТЫРМА ӘРЕКЕТІН АЛЫП ТАСТАУ
# ==========================================================

next_student_button9.on_click(
    next_student_click11,
    remove=True
)


# Жаңа әрекетті қосу
next_student_button9.on_click(
    next_student_click16
)


print("✅ «Келесі оқушы» батырмасы толық жаңартылды.")

✅ «Келесі оқушы» батырмасы толық жаңартылды.

In [ ]:
# ==========================================================
# 🎮 KobeitDos AI — ЖАҢАРТЫЛҒАН ОЙЫН
# ==========================================================

import random

game17 = {
    "q": 1,
    "score": 0,
    "lives": 3,
    "a": 0,
    "b": 0,
    "correct": 0
}


game_html17 = widgets.HTML()

game_input17 = widgets.Text(
    description="✏️ Жауап:",
    placeholder="Жауабыңды жаз...",
    layout=widgets.Layout(width="350px")
)

game_message17 = widgets.HTML()


# ----------------------------------------------------------
# ОЙЫНДЫ БАСТАУ
# ----------------------------------------------------------

def game_start17():

    game17["q"] = 1
    game17["score"] = 0
    game17["lives"] = 3

    game_input17.value = ""
    game_input17.layout.display = ""

    game_message17.value = """
    <div style="
        background:#E3F2FD;
        padding:12px;
        border-radius:12px;
        text-align:center;
    ">
        🚀 Ойын басталды! Сәттілік!
    </div>
    """

    game_question17()


# ----------------------------------------------------------
# ЖАҢА СҰРАҚ
# ----------------------------------------------------------

def game_question17():

    if game17["q"] > 5 or game17["lives"] <= 0:
        game_finish17()
        return

    a = random.randint(2, 9)
    b = random.randint(2, 9)

    game17["a"] = a
    game17["b"] = b
    game17["correct"] = a * b

    hearts = "❤️" * game17["lives"]

    game_html17.value = f"""
    <div style="
        background:linear-gradient(135deg,#E3F2FD,#F3E5F5);
        padding:25px;
        border-radius:20px;
        text-align:center;
    ">

        <h1>🎮 Көбейту жарысы</h1>

        <div style="
            display:flex;
            justify-content:center;
            gap:35px;
            flex-wrap:wrap;
            font-size:18px;
        ">

            <div>
                📝 Сұрақ:
                <b>{game17["q"]} / 5</b>
            </div>

            <div>
                ⭐ Ұпай:
                <b>{game17["score"]}</b>
            </div>

            <div>
                {hearts}
            </div>

        </div>

        <div style="
            background:white;
            margin:20px auto;
            padding:22px;
            border-radius:18px;
            max-width:400px;
        ">

            <p style="
                margin:0;
                color:#666;
            ">
                Неше болады?
            </p>

            <h1 style="
                font-size:42px;
                color:#3949AB;
                margin:10px;
            ">
                {a} × {b} = ?
            </h1>

        </div>

        <p>
            Жауабыңды жазып,
            <b>Enter</b> бас.
        </p>

    </div>
    """


# ----------------------------------------------------------
# ЖАУАПТЫ ТЕКСЕРУ
# ----------------------------------------------------------

def game_check17(widget):

    text = game_input17.value.strip()

    if text == "":
        return

    try:
        answer = int(text)

    except:

        game_message17.value = """
        <div style="
            background:#FFF3E0;
            padding:12px;
            border-radius:12px;
            text-align:center;
        ">
            ⚠️ Жауапты санмен жаз.
        </div>
        """

        game_input17.value = ""
        return


    # ДҰРЫС ЖАУАП
    if answer == game17["correct"]:

        game17["score"] += 1

        game_message17.value = """
        <div style="
            background:#E8F5E9;
            padding:12px;
            border-radius:12px;
            text-align:center;
            font-size:18px;
        ">
            🌟 Дұрыс! Жарайсың!
        </div>
        """


    # ҚАТЕ ЖАУАП
    else:

        game17["lives"] -= 1

        correct = game17["correct"]

        game_message17.value = f"""
        <div style="
            background:#FFEBEE;
            padding:12px;
            border-radius:12px;
            text-align:center;
            font-size:18px;
        ">
            💡 Дұрыс жауап:
            <b>{correct}</b>
        </div>
        """


    game17["q"] += 1

    game_input17.value = ""

    game_question17()


# Enter арқылы тексеру
game_input17.on_submit(game_check17)


# ----------------------------------------------------------
# ОЙЫН СОҢЫ
# ----------------------------------------------------------

def game_finish17():

    score = game17["score"]

    game_input17.layout.display = "none"


    if score == 5:

        level = "🏆 Көбейту шебері!"
        message = "Тамаша! Барлық жауап дұрыс!"

    elif score >= 3:

        level = "🌟 Жарайсың!"
        message = "Жақсы нәтиже! Тағы ойнап көр."

    else:

        level = "💪 Жаттығуды жалғастыр!"
        message = "Көбейту кестесін тағы қайталайық."


    game_html17.value = f"""
    <div style="
        background:linear-gradient(135deg,#FFF8E1,#E8F5E9);
        padding:30px;
        border-radius:20px;
        text-align:center;
    ">

        <div style="font-size:55px;">
            🎉
        </div>

        <h1>
            Ойын аяқталды!
        </h1>

        <h2>
            ⭐ {score} / 5
        </h2>

        <h2 style="color:#3949AB;">
            {level}
        </h2>

        <p style="font-size:18px;">
            {message}
        </p>

    </div>
    """


    game_message17.value = ""


# ----------------------------------------------------------
# ОЙЫН БЛОГЫ
# ----------------------------------------------------------

game_box17 = widgets.VBox([
    game_html17,
    game_input17,
    game_message17
])

game_box17.layout.display = "none"


# ==========================================================
# ПЛАТФОРМАҒА ЖАҢА ОЙЫНДЫ ҚОСУ
# ==========================================================

KobeitDos_AI.children = (
    app_title,
    student_box5,
    app_menu,
    home_box14,
    learn_box2,
    game_box17,
    diag_box2,
    practice_box3,
    result_full15,
    class_result_full13
)


# ==========================================================
# МӘЗІРДІ ЖАҢАРТУ
# ==========================================================

app_menu.unobserve(
    app_change15,
    names="value"
)


def app_change17(change):

    section = change["new"]

    home_box14.layout.display = "none"
    learn_box2.layout.display = "none"
    game_box17.layout.display = "none"
    diag_box2.layout.display = "none"
    practice_box3.layout.display = "none"
    result_full15.layout.display = "none"
    class_result_full13.layout.display = "none"


    if section == "home":

        home_box14.layout.display = ""


    elif section == "learn":

        learn_box2.layout.display = ""


    elif section == "game":

        game_box17.layout.display = ""
        game_start17()


    elif section == "diagnostic":

        diag_box2.layout.display = ""
        diagnostic_start2()


    elif section == "practice":

        practice_box3.layout.display = ""
        practice_start3()


    elif section == "result":

        result_full15.layout.display = ""
        show_result5()


    elif section == "class_result":

        class_result_full13.layout.display = ""
        show_class_result12()
        show_class_chart13()


app_menu.observe(
    app_change17,
    names="value"
)


# Қазіргі бөлімді қайта көрсету
app_change17({
    "new": app_menu.value
})


print("✅ Жаңа ойын бөлімі қосылды.")

✅ Жаңа ойын бөлімі қосылды.

In [ ]:
# ==========================================================
# 📚 KobeitDos AI — ЖАҢАРТЫЛҒАН «ҮЙРЕНУ» БӨЛІМІ
# ==========================================================

# Тақырып
learn_title18 = widgets.HTML(
    value="""
    <div style="
        background:linear-gradient(135deg,#E3F2FD,#E8EAF6);
        padding:22px;
        border-radius:20px;
        text-align:center;
    ">
        <div style="font-size:45px;">📚</div>

        <h1 style="
            color:#3949AB;
            margin:5px;
        ">
            Көбейту кестесін үйренейік!
        </h1>

        <p style="font-size:18px;">
            Төменнен үйренгің келетін
            көбейту кестесін таңда.
        </p>
    </div>
    """
)


# ----------------------------------------------------------
# КЕСТЕНІ ТАҢДАУ
# ----------------------------------------------------------

learn_select18 = widgets.Dropdown(
    options=[
        ("2-ге көбейту", 2),
        ("3-ке көбейту", 3),
        ("4-ке көбейту", 4),
        ("5-ке көбейту", 5),
        ("6-ға көбейту", 6),
        ("7-ге көбейту", 7),
        ("8-ге көбейту", 8),
        ("9-ға көбейту", 9)
    ],
    value=2,
    description="🔢 Кесте:",
    layout=widgets.Layout(width="350px")
)


# Нәтиже шығатын жер
learn_content18 = widgets.HTML()


# ----------------------------------------------------------
# КЕСТЕНІ КӨРСЕТУ
# ----------------------------------------------------------

def show_table18(number):

    cards = ""

    for i in range(1, 11):

        answer = number * i

        cards += f"""
        <div style="
            background:white;
            padding:15px 8px;
            border-radius:15px;
            text-align:center;
            box-shadow:0 2px 6px rgba(0,0,0,0.08);
        ">

            <div style="
                font-size:20px;
                color:#3949AB;
                font-weight:bold;
            ">
                {number} × {i}
            </div>

            <div style="
                font-size:25px;
                margin-top:5px;
            ">
                = {answer}
            </div>

        </div>
        """


    # Әр кестеге шағын есте сақтау кеңесі
    tips = {

        2: """
        2-ге көбейткенде санды екі рет қосамыз.
        Мысалы: 2 × 6 = 6 + 6 = 12.
        """,

        3: """
        3-ке көбейту — бір санды үш рет қосу.
        Мысалы: 3 × 4 = 4 + 4 + 4 = 12.
        """,

        4: """
        4-ке көбейтуді екі рет екі еселеу арқылы
        табуға болады. Мысалы: 4 × 6:
        6 → 12 → 24.
        """,

        5: """
        5-ке көбейту нәтижелері әрқашан
        0 немесе 5 цифрымен аяқталады.
        """,

        6: """
        6-ға көбейтуді 5 топ және тағы 1 топ
        деп ойлауға болады.
        Мысалы: 6 × 7 = 5 × 7 + 7.
        """,

        7: """
        7 кестесін шағын бөліктермен қайтала:
        алдымен 7×2, 7×3, 7×4,
        кейін қалғандарын қос.
        """,

        8: """
        8-ге көбейтуді үш рет екі еселеу
        арқылы тексеруге болады.
        Мысалы: 8 × 3: 3 → 6 → 12 → 24.
        """,

        9: """
        9-ға көбейтудің бір үлгісі:
        9, 18, 27, 36, 45...
        Нәтижелер әр жолы 9-ға артып отырады.
        """
    }


    learn_content18.value = f"""
    <div style="
        background:#F7F8FF;
        padding:22px;
        border-radius:20px;
        margin-top:12px;
    ">

        <h2 style="
            text-align:center;
            color:#3949AB;
        ">
            ✖️ {number}-ге көбейту кестесі
        </h2>


        <div style="
            display:grid;
            grid-template-columns:
            repeat(auto-fit,minmax(120px,1fr));
            gap:10px;
        ">

            {cards}

        </div>


        <div style="
            background:#FFF8E1;
            padding:18px;
            border-radius:16px;
            margin-top:18px;
        ">

            <h3 style="
                text-align:center;
                margin-top:0;
            ">
                💡 Есте сақтау тәсілі
            </h3>

            <p style="
                font-size:17px;
                line-height:1.6;
                text-align:center;
            ">
                {tips[number]}
            </p>

        </div>


        <div style="
            background:#E8F5E9;
            padding:15px;
            border-radius:16px;
            margin-top:12px;
            text-align:center;
        ">

            ⭐ Кестені дауыстап бірнеше рет қайтала.
            Содан кейін 🎮 Ойын бөлімінде өзіңді тексер!

        </div>

    </div>
    """


# Таңдау өзгергенде
def learn_change18(change):

    if change["name"] == "value":

        show_table18(
            change["new"]
        )


learn_select18.observe(
    learn_change18,
    names="value"
)


# Алғашқы 2 кестесін көрсету
show_table18(2)


# Үйрену блогы
learn_box18 = widgets.VBox([
    learn_title18,
    learn_select18,
    learn_content18
])

learn_box18.layout.display = "none"


# ==========================================================
# ПЛАТФОРМАҒА ЖАҢА ҮЙРЕНУ БӨЛІМІН ҚОСУ
# ==========================================================

KobeitDos_AI.children = (
    app_title,
    student_box5,
    app_menu,
    home_box14,
    learn_box18,
    game_box17,
    diag_box2,
    practice_box3,
    result_full15,
    class_result_full13
)


# ==========================================================
# МӘЗІРДІ ЖАҢАРТУ
# ==========================================================

app_menu.unobserve(
    app_change17,
    names="value"
)


def app_change18(change):

    section = change["new"]

    home_box14.layout.display = "none"
    learn_box18.layout.display = "none"
    game_box17.layout.display = "none"
    diag_box2.layout.display = "none"
    practice_box3.layout.display = "none"
    result_full15.layout.display = "none"
    class_result_full13.layout.display = "none"


    if section == "home":

        home_box14.layout.display = ""


    elif section == "learn":

        learn_box18.layout.display = ""


    elif section == "game":

        game_box17.layout.display = ""
        game_start17()


    elif section == "diagnostic":

        diag_box2.layout.display = ""
        diagnostic_start2()


    elif section == "practice":

        practice_box3.layout.display = ""
        practice_start3()


    elif section == "result":

        result_full15.layout.display = ""
        show_result5()


    elif section == "class_result":

        class_result_full13.layout.display = ""
        show_class_result12()
        show_class_chart13()


app_menu.observe(
    app_change18,
    names="value"
)


# Қазіргі таңдалған бөлімді қайта көрсету
app_change18({
    "new": app_menu.value
})


print("✅ «Үйрену» бөлімі жаңартылды.")

✅ «Үйрену» бөлімі жаңартылды.

In [ ]:
# ==========================================================
# 🧠 KobeitDos AI — ДИАГНОСТИКА ДИЗАЙНЫ
# ==========================================================

diag_header19 = widgets.HTML(
    value="""
    <div style="
        background:linear-gradient(135deg,#E8EAF6,#E3F2FD);
        padding:25px;
        border-radius:20px;
        text-align:center;
        margin-bottom:12px;
    ">

        <div style="font-size:48px;">
            🧠
        </div>

        <h1 style="
            color:#3949AB;
            margin:5px;
        ">
            Ақылды диагностика
        </h1>

        <p style="
            font-size:18px;
            margin-bottom:8px;
        ">
            Қай көбейту кестесін жақсы білетініңді
            анықтайық!
        </p>

        <div style="
            background:white;
            padding:12px;
            border-radius:14px;
            margin-top:15px;
        ">
            📝 16 сұрақ
            &nbsp;&nbsp;•&nbsp;&nbsp;
            🔢 2–9 кестелері
            &nbsp;&nbsp;•&nbsp;&nbsp;
            🤖 AI талдау
        </div>

    </div>
    """
)


diag_info19 = widgets.HTML(
    value="""
    <div style="
        background:#FFF8E1;
        padding:14px;
        border-radius:14px;
        margin-bottom:10px;
        text-align:center;
    ">
        💡 <b>Ереже:</b>
        есепті өзің шығар.
        Жауабыңды жазып,
        <b>Enter</b> бас.
    </div>
    """
)


# ----------------------------------------------------------
# БҰРЫНҒЫ ДИАГНОСТИКА ЭЛЕМЕНТТЕРІН ПАЙДАЛАНАМЫЗ
# ----------------------------------------------------------

diag_box19 = widgets.VBox([
    diag_header19,
    diag_info19,
    diag_html2,
    diag_input2,
    diag_message2
])

diag_box19.layout.display = "none"


# Жауап енгізетін жолды сәл үлкейтеміз
diag_input2.layout = widgets.Layout(
    width="380px",
    margin="10px 0px"
)


# ==========================================================
# ПЛАТФОРМАҒА ЖАҢА ДИАГНОСТИКА БӨЛІМІН ҚОСУ
# ==========================================================

KobeitDos_AI.children = (
    app_title,
    student_box5,
    app_menu,
    home_box14,
    learn_box18,
    game_box17,
    diag_box19,
    practice_box3,
    result_full15,
    class_result_full13
)


# ==========================================================
# МӘЗІРДІ ЖАҢАРТУ
# ==========================================================

app_menu.unobserve(
    app_change18,
    names="value"
)


def app_change19(change):

    section = change["new"]

    # Барлық бөлімді жасырамыз
    home_box14.layout.display = "none"
    learn_box18.layout.display = "none"
    game_box17.layout.display = "none"
    diag_box19.layout.display = "none"
    practice_box3.layout.display = "none"
    result_full15.layout.display = "none"
    class_result_full13.layout.display = "none"


    # Таңдалған бөлімді ашамыз
    if section == "home":

        home_box14.layout.display = ""


    elif section == "learn":

        learn_box18.layout.display = ""


    elif section == "game":

        game_box17.layout.display = ""
        game_start17()


    elif section == "diagnostic":

        diag_box19.layout.display = ""

        # Бұрынғы диагностика функциясы
        diagnostic_start2()


    elif section == "practice":

        practice_box3.layout.display = ""
        practice_start3()


    elif section == "result":

        result_full15.layout.display = ""
        show_result5()


    elif section == "class_result":

        class_result_full13.layout.display = ""
        show_class_result12()
        show_class_chart13()


app_menu.observe(
    app_change19,
    names="value"
)


# Қазіргі бөлімді көрсету
app_change19({
    "new": app_menu.value
})


print("✅ Диагностика дизайны жаңартылды.")

✅ Диагностика дизайны жаңартылды.

In [ ]:
# ==========================================================
# 🎯 KobeitDos AI — ЖЕКЕ ЖАТТЫҒУ ДИЗАЙНЫ
# ==========================================================

practice_header20 = widgets.HTML(
    value="""
    <div style="
        background:linear-gradient(135deg,#E8F5E9,#E3F2FD);
        padding:25px;
        border-radius:20px;
        text-align:center;
        margin-bottom:12px;
    ">

        <div style="font-size:48px;">
            🎯
        </div>

        <h1 style="
            color:#2E7D32;
            margin:5px;
        ">
            Жеке жаттығу
        </h1>

        <p style="
            font-size:18px;
            margin-bottom:8px;
        ">
            KobeitDos AI сенің диагностика нәтижелеріңді
            талдап, саған арнайы тапсырмалар дайындайды.
        </p>

        <div style="
            background:white;
            padding:12px;
            border-radius:14px;
            margin-top:15px;
        ">
            🤖 AI талдау
            &nbsp;&nbsp;•&nbsp;&nbsp;
            🎯 Әлсіз кесте
            &nbsp;&nbsp;•&nbsp;&nbsp;
            📝 5 тапсырма
            &nbsp;&nbsp;•&nbsp;&nbsp;
            📈 Нәтиже
        </div>

    </div>
    """
)


practice_info20 = widgets.HTML(
    value="""
    <div style="
        background:#FFF8E1;
        padding:15px;
        border-radius:14px;
        text-align:center;
        margin-bottom:10px;
    ">

        💡 <b>Қалай жұмыс істейді?</b><br>

        Алдымен 🧠 Диагностикадан өт.
        Жүйе ең әлсіз көбейту кестеңді анықтайды.
        Осы бөлімде дәл сол кестеден
        арнайы тапсырмалар беріледі.

    </div>
    """
)


# ----------------------------------------------------------
# БҰРЫНҒЫ ЖАТТЫҒУ ЭЛЕМЕНТТЕРІН ҚОЛДАНАМЫЗ
# ----------------------------------------------------------

practice_box20 = widgets.VBox([
    practice_header20,
    practice_info20,
    practice_html3,
    practice_input3,
    practice_message3
])

practice_box20.layout.display = "none"


# Жауап жолын сәл үлкейту
practice_input3.layout = widgets.Layout(
    width="380px",
    margin="10px 0px"
)


# ==========================================================
# ПЛАТФОРМАҒА ЖАҢА БӨЛІМДІ ҚОСУ
# ==========================================================

KobeitDos_AI.children = (
    app_title,
    student_box5,
    app_menu,
    home_box14,
    learn_box18,
    game_box17,
    diag_box19,
    practice_box20,
    result_full15,
    class_result_full13
)


# ==========================================================
# МӘЗІРДІ ЖАҢАРТУ
# ==========================================================

app_menu.unobserve(
    app_change19,
    names="value"
)


def app_change20(change):

    section = change["new"]

    # Барлық бөлімді жасыру
    home_box14.layout.display = "none"
    learn_box18.layout.display = "none"
    game_box17.layout.display = "none"
    diag_box19.layout.display = "none"
    practice_box20.layout.display = "none"
    result_full15.layout.display = "none"
    class_result_full13.layout.display = "none"


    # Таңдалған бөлімді көрсету
    if section == "home":

        home_box14.layout.display = ""


    elif section == "learn":

        learn_box18.layout.display = ""


    elif section == "game":

        game_box17.layout.display = ""
        game_start17()


    elif section == "diagnostic":

        diag_box19.layout.display = ""
        diagnostic_start2()


    elif section == "practice":

        practice_box20.layout.display = ""

        # Бұрынғы жеке жаттығу функциясы
        practice_start3()


    elif section == "result":

        result_full15.layout.display = ""
        show_result5()


    elif section == "class_result":

        class_result_full13.layout.display = ""
        show_class_result12()
        show_class_chart13()


app_menu.observe(
    app_change20,
    names="value"
)


# Қазіргі ашық тұрған бөлімді қайта көрсету
app_change20({
    "new": app_menu.value
})


print("✅ «Жеке жаттығу» дизайны жаңартылды.")

✅ «Жеке жаттығу» дизайны жаңартылды.

In [ ]:
# ==========================================================
# 📊 KobeitDos AI — ОҚУШЫНЫҢ ЖЕКЕ ЕСЕБІ
# ==========================================================

def show_result21():

    global result_box4

    # ------------------------------------------------------
    # 1. ОҚУШЫ АТЫ
    # ------------------------------------------------------

    name = student_name5.strip()

    if name == "":
        name = "Оқушы"


    # ------------------------------------------------------
    # 2. ДИАГНОСТИКА БАР МА?
    # ------------------------------------------------------

    if not diagnostic_percent2:

        result_box4.value = f"""
        <div style="
            background:#FFF3E0;
            padding:30px;
            border-radius:20px;
            text-align:center;
        ">

            <div style="font-size:50px;">⚠️</div>

            <h2>
                {name}, нәтиже әлі дайын емес
            </h2>

            <p style="font-size:18px;">
                Алдымен 🧠 Диагностикадан өт.
            </p>

        </div>
        """

        return


    # ------------------------------------------------------
    # 3. 2–9 КЕСТЕЛЕРІНІҢ НӘТИЖЕЛЕРІ
    # ------------------------------------------------------

    table_cards = ""

    for number in range(2, 10):

        percent = diagnostic_percent2.get(number, 0)

        if percent >= 80:
            icon = "🌟"
            status = "Өте жақсы"

        elif percent >= 50:
            icon = "👍"
            status = "Жақсы"

        else:
            icon = "🎯"
            status = "Жаттығу керек"


        table_cards += f"""
        <div style="
            background:white;
            padding:14px;
            border-radius:15px;
            box-shadow:0 2px 6px rgba(0,0,0,0.08);
        ">

            <div style="
                display:flex;
                justify-content:space-between;
                align-items:center;
            ">

                <b style="font-size:18px;">
                    {icon} {number} кестесі
                </b>

                <b style="
                    color:#3949AB;
                    font-size:18px;
                ">
                    {percent:.0f}%
                </b>

            </div>


            <div style="
                background:#EEEEEE;
                height:12px;
                border-radius:10px;
                margin-top:10px;
                overflow:hidden;
            ">

                <div style="
                    width:{percent}%;
                    height:12px;
                    background:linear-gradient(
                        90deg,
                        #42A5F5,
                        #66BB6A
                    );
                    border-radius:10px;
                ">
                </div>

            </div>


            <div style="
                margin-top:7px;
                font-size:13px;
                color:#666;
            ">
                {status}
            </div>

        </div>
        """


    # ------------------------------------------------------
    # 4. ЕҢ ӘЛСІЗ КЕСТЕ
    # ------------------------------------------------------

    weak = weakest_number2

    if weak is not None:

        weak_percent = diagnostic_percent2.get(
            weak,
            0
        )

        weak_block = f"""
        <div style="
            background:#FFF3E0;
            padding:18px;
            border-radius:16px;
            margin-top:15px;
            text-align:center;
        ">

            <h3 style="
                margin-top:0;
                color:#E65100;
            ">
                🎯 AI анықтаған әлсіз кесте
            </h3>

            <div style="
                font-size:28px;
                font-weight:bold;
            ">
                {weak}-ге көбейту
            </div>

            <p>
                Диагностика нәтижесі:
                <b>{weak_percent:.0f}%</b>
            </p>

        </div>
        """

    else:

        weak_block = ""


    # ------------------------------------------------------
    # 5. ЖАТТЫҒУ НӘТИЖЕСІ
    # ------------------------------------------------------

    comparison_block = ""

    if (
        practice3["number"] is not None
        and practice3["q"] > 5
    ):

        before = diagnostic_percent2.get(
            practice3["number"],
            0
        )

        after = practice_percent3

        difference = after - before


        if difference > 0:

            change_text = (
                f"📈 +{difference:.0f}% жақсарды"
            )

            ai_text = """
            Жаттығудан кейін нәтиже жақсарды.
            Жеке тапсырмалар пайдалы болды.
            """

        elif difference == 0:

            change_text = "➡️ Нәтиже өзгерген жоқ"

            ai_text = """
            Нәтиже әзірге өзгерген жоқ.
            Осы кестені тағы қайталау ұсынылады.
            """

        else:

            change_text = (
                f"🔄 {difference:.0f}%"
            )

            ai_text = """
            Бұл кестеге қосымша жаттығу қажет.
            Қайта үйреніп, тағы бір рет орында.
            """


        comparison_block = f"""
        <div style="
            background:#E8F5E9;
            padding:20px;
            border-radius:18px;
            margin-top:15px;
        ">

            <h3 style="
                text-align:center;
                margin-top:0;
                color:#2E7D32;
            ">
                📈 Жаттығу нәтижесі
            </h3>


            <div style="
                display:flex;
                justify-content:center;
                gap:15px;
                flex-wrap:wrap;
            ">


                <div style="
                    background:white;
                    padding:18px;
                    border-radius:15px;
                    min-width:160px;
                    text-align:center;
                ">

                    <div>
                        🧠 Диагностика
                    </div>

                    <div style="
                        font-size:30px;
                        font-weight:bold;
                        color:#EF6C00;
                    ">
                        {before:.0f}%
                    </div>

                </div>


                <div style="
                    background:white;
                    padding:18px;
                    border-radius:15px;
                    min-width:160px;
                    text-align:center;
                ">

                    <div>
                        🎯 Жаттығудан кейін
                    </div>

                    <div style="
                        font-size:30px;
                        font-weight:bold;
                        color:#2E7D32;
                    ">
                        {after:.0f}%
                    </div>

                </div>

            </div>


            <h3 style="
                text-align:center;
                margin-bottom:5px;
            ">
                {change_text}
            </h3>


            <div style="
                background:white;
                padding:15px;
                border-radius:14px;
                margin-top:15px;
                text-align:center;
            ">

                🤖 <b>KobeitDos AI қорытындысы:</b>

                <br><br>

                {ai_text}

            </div>

        </div>
        """


    # ------------------------------------------------------
    # 6. БАРЛЫҒЫН БІР ЭКРАНҒА ШЫҒАРУ
    # ------------------------------------------------------

    result_box4.value = f"""
    <div style="
        background:#F7F8FF;
        padding:25px;
        border-radius:22px;
    ">

        <div style="
            background:linear-gradient(
                135deg,
                #3949AB,
                #5C6BC0
            );
            color:white;
            padding:25px;
            border-radius:20px;
            text-align:center;
        ">

            <div style="font-size:45px;">
                📊
            </div>

            <h1 style="margin:5px;">
                Менің нәтижем
            </h1>

            <h2 style="margin:8px;">
                👤 {name}
            </h2>

            <p style="margin-bottom:0;">
                Жеке оқу есебі
            </p>

        </div>


        <h2 style="
            text-align:center;
            color:#3949AB;
            margin-top:25px;
        ">
            🔢 Көбейту кестелері бойынша нәтиже
        </h2>


        <div style="
            display:grid;
            grid-template-columns:
            repeat(auto-fit,minmax(210px,1fr));
            gap:12px;
        ">

            {table_cards}

        </div>


        {weak_block}

        {comparison_block}


        <div style="
            background:#E3F2FD;
            padding:15px;
            border-radius:15px;
            margin-top:15px;
            text-align:center;
        ">

            💡 <b>Ұсыныс:</b>
            әлсіз кестені күн сайын қысқа уақыт
            қайталап, 🎮 Ойын арқылы бекіт.

        </div>

    </div>
    """


# ==========================================================
# МӘЗІРДЕ ЕСКІ ФУНКЦИЯНЫ ЖАҢАСЫНА АУЫСТЫРУ
# ==========================================================

app_menu.unobserve(
    app_change20,
    names="value"
)


def app_change21(change):

    section = change["new"]

    home_box14.layout.display = "none"
    learn_box18.layout.display = "none"
    game_box17.layout.display = "none"
    diag_box19.layout.display = "none"
    practice_box20.layout.display = "none"
    result_full15.layout.display = "none"
    class_result_full13.layout.display = "none"


    if section == "home":

        home_box14.layout.display = ""


    elif section == "learn":

        learn_box18.layout.display = ""


    elif section == "game":

        game_box17.layout.display = ""
        game_start17()


    elif section == "diagnostic":

        diag_box19.layout.display = ""
        diagnostic_start2()


    elif section == "practice":

        practice_box20.layout.display = ""
        practice_start3()


    elif section == "result":

        result_full15.layout.display = ""

        # ЖАҢА ЖЕКЕ ЕСЕП
        show_result21()


    elif section == "class_result":

        class_result_full13.layout.display = ""
        show_class_result12()
        show_class_chart13()


app_menu.observe(
    app_change21,
    names="value"
)


# Қазіргі бөлімді жаңарту
app_change21({
    "new": app_menu.value
})


print("✅ «Менің нәтижем» беті жаңартылды.")

✅ «Менің нәтижем» беті жаңартылды.

In [ ]:
# 📊 «Менің нәтижем» бетін көрсету қатесін түзету

result_box4.layout.display = ""
result_full15.layout.display = ""

show_result21()

print("✅ «Менің нәтижем» көрсету қатесі түзетілді.")

✅ «Менің нәтижем» көрсету қатесі түзетілді.

In [ ]:
# 👤 Оқушы атын «Менің нәтижем» бетімен дұрыс байланыстыру

def show_result22():

    # Атын тікелей енгізу жолағынан аламыз
    name = student_input5.value.strip()

    if name == "":
        name = "Оқушы"

    # student_name5-ті уақытша дұрыс атпен жаңартамыз
    global student_name5
    student_name5 = name

    # Бұрын жасаған әдемі нәтиже бетін шығарамыз
    show_result21()


# Мәзірдегі нәтиже функциясын жаңарту
app_menu.unobserve(
    app_change21,
    names="value"
)


def app_change22(change):

    section = change["new"]

    home_box14.layout.display = "none"
    learn_box18.layout.display = "none"
    game_box17.layout.display = "none"
    diag_box19.layout.display = "none"
    practice_box20.layout.display = "none"
    result_full15.layout.display = "none"
    class_result_full13.layout.display = "none"

    if section == "home":
        home_box14.layout.display = ""

    elif section == "learn":
        learn_box18.layout.display = ""

    elif section == "game":
        game_box17.layout.display = ""
        game_start17()

    elif section == "diagnostic":
        diag_box19.layout.display = ""
        diagnostic_start2()

    elif section == "practice":
        practice_box20.layout.display = ""
        practice_start3()

    elif section == "result":
        result_full15.layout.display = ""
        result_box4.layout.display = ""

        # ЖАҢАРТЫЛҒАН НӘТИЖЕ
        show_result22()

    elif section == "class_result":
        class_result_full13.layout.display = ""
        show_class_result12()
        show_class_chart13()


app_menu.observe(
    app_change22,
    names="value"
)

print("✅ Оқушының аты нәтиже бетімен байланыстырылды.")

✅ Оқушының аты нәтиже бетімен байланыстырылды.

In [ ]:
# 👤 Нәтиже бетіндегі оқушы атын түзету

student_name5 = student_input5.value.strip()

# Егер аты енгізілген болса, нәтижені қайта шығару
if student_name5 != "":
    show_result21()
    result_box4.layout.display = ""
    result_full15.layout.display = ""

    print("✅ Нәтиже бетіндегі оқушы аты:", student_name5)

else:
    print("⚠️ Алдымен оқушының атын енгізіңіз.")

✅ Нәтиже бетіндегі оқушы аты: Айда

In [ ]:
# ==========================================================
# 📈 KobeitDos AI — СЫНЫП НӘТИЖЕСІН ТАЛДАУ
# ==========================================================

import pandas as pd
import os

class_result23 = widgets.HTML()


def show_class_result23():

    # Excel файлы бар ма?
    if not os.path.exists(file_path10):

        class_result23.value = """
        <div style="
            background:#FFF3E0;
            padding:30px;
            border-radius:20px;
            text-align:center;
        ">
            <div style="font-size:50px;">📂</div>

            <h2>Әзірге нәтиже жоқ</h2>

            <p>
                Алдымен оқушылар диагностика мен
                жеке жаттығудан өтіп,
                нәтижелерін сақтау керек.
            </p>
        </div>
        """

        return


    # Excel оқу
    df = pd.read_excel(file_path10)


    if len(df) == 0:

        class_result23.value = """
        <div style="
            background:#FFF3E0;
            padding:25px;
            border-radius:20px;
            text-align:center;
        ">
            📊 Сақталған оқушы нәтижесі жоқ.
        </div>
        """

        return


    # ======================================================
    # НЕГІЗГІ КӨРСЕТКІШТЕР
    # ======================================================

    student_count = len(df)

    avg_before = df[
        "Диагностика (%)"
    ].mean()

    avg_after = df[
        "Жаттығудан кейін (%)"
    ].mean()

    avg_change = df[
        "Өзгеріс (%)"
    ].mean()


    # Ең жиі әлсіз болған кесте
    weak_counts = df[
        "Әлсіз кесте"
    ].value_counts()

    most_difficult = int(
        weak_counts.index[0]
    )


    # Нәтижесі жақсарған оқушылар
    improved_count = int(
        (df["Өзгеріс (%)"] > 0).sum()
    )


    # ======================================================
    # ОҚУШЫЛАР КЕСТЕСІ
    # ======================================================

    rows = ""

    for _, row in df.iterrows():

        change = row["Өзгеріс (%)"]

        if change > 0:
            change_text = f"📈 +{change:.0f}%"

        elif change == 0:
            change_text = "➡️ 0%"

        else:
            change_text = f"🔄 {change:.0f}%"


        rows += f"""
        <tr>

            <td style="
                padding:11px;
                border-bottom:1px solid #ddd;
            ">
                👤 {row["Оқушы"]}
            </td>

            <td style="
                padding:11px;
                text-align:center;
                border-bottom:1px solid #ddd;
            ">
                {int(row["Әлсіз кесте"])}
            </td>

            <td style="
                padding:11px;
                text-align:center;
                border-bottom:1px solid #ddd;
            ">
                {row["Диагностика (%)"]:.0f}%
            </td>

            <td style="
                padding:11px;
                text-align:center;
                border-bottom:1px solid #ddd;
            ">
                {row["Жаттығудан кейін (%)"]:.0f}%
            </td>

            <td style="
                padding:11px;
                text-align:center;
                border-bottom:1px solid #ddd;
                font-weight:bold;
            ">
                {change_text}
            </td>

        </tr>
        """


    # ======================================================
    # AI ҚОРЫТЫНДЫСЫ
    # ======================================================

    if avg_change > 0:

        ai_text = f"""
        Оқушылардың орташа нәтижесі
        <b>{avg_change:.1f}%</b>-ға өскен.
        Ең жиі қиындық туғызғаны —
        <b>{most_difficult}-ге көбейту кестесі</b>.
        """

    elif avg_change == 0:

        ai_text = f"""
        Орташа нәтиже өзгермеген.
        <b>{most_difficult}-ге көбейту кестесіне</b>
        қосымша жаттығу қажет.
        """

    else:

        ai_text = f"""
        Нәтижелер қосымша жаттығу қажет екенін
        көрсетіп тұр. Әсіресе
        <b>{most_difficult}-ге көбейту кестесіне</b>
        назар аудару керек.
        """


    # ======================================================
    # БҮКІЛ БЕТ
    # ======================================================

    class_result23.value = f"""
    <div style="
        background:#F7F8FF;
        padding:25px;
        border-radius:22px;
    ">

        <div style="
            background:linear-gradient(
                135deg,
                #3949AB,
                #5C6BC0
            );
            color:white;
            padding:25px;
            border-radius:20px;
            text-align:center;
        ">

            <div style="font-size:48px;">
                📈
            </div>

            <h1 style="margin:5px;">
                Сынып нәтижесі
            </h1>

            <p style="font-size:17px;">
                KobeitDos AI жалпы талдауы
            </p>

        </div>


        <div style="
            display:grid;
            grid-template-columns:
            repeat(auto-fit,minmax(180px,1fr));
            gap:12px;
            margin-top:20px;
        ">


            <div style="
                background:white;
                padding:18px;
                border-radius:16px;
                text-align:center;
            ">
                <div>👥 Оқушы саны</div>

                <h2 style="color:#3949AB;">
                    {student_count}
                </h2>
            </div>


            <div style="
                background:white;
                padding:18px;
                border-radius:16px;
                text-align:center;
            ">
                <div>🧠 Бастапқы орташа</div>

                <h2 style="color:#EF6C00;">
                    {avg_before:.1f}%
                </h2>
            </div>


            <div style="
                background:white;
                padding:18px;
                border-radius:16px;
                text-align:center;
            ">
                <div>🎯 Жаттығудан кейін</div>

                <h2 style="color:#2E7D32;">
                    {avg_after:.1f}%
                </h2>
            </div>


            <div style="
                background:white;
                padding:18px;
                border-radius:16px;
                text-align:center;
            ">
                <div>📈 Орташа өзгеріс</div>

                <h2 style="color:#00897B;">
                    {avg_change:+.1f}%
                </h2>
            </div>

        </div>


        <div style="
            display:flex;
            gap:12px;
            flex-wrap:wrap;
            margin-top:15px;
        ">

            <div style="
                background:#FFF3E0;
                padding:16px;
                border-radius:15px;
                flex:1;
                min-width:220px;
                text-align:center;
            ">

                🎯 <b>Ең жиі әлсіз кесте</b>

                <div style="
                    font-size:27px;
                    margin-top:5px;
                ">
                    {most_difficult}-ге көбейту
                </div>

            </div>


            <div style="
                background:#E8F5E9;
                padding:16px;
                border-radius:15px;
                flex:1;
                min-width:220px;
                text-align:center;
            ">

                🌟 <b>Нәтижесі жақсарған</b>

                <div style="
                    font-size:27px;
                    margin-top:5px;
                ">
                    {improved_count} / {student_count}
                </div>

            </div>

        </div>


        <h2 style="
            text-align:center;
            color:#3949AB;
            margin-top:25px;
        ">
            📋 Оқушылар нәтижесі
        </h2>


        <div style="
            overflow-x:auto;
            background:white;
            border-radius:16px;
            padding:10px;
        ">

            <table style="
                width:100%;
                border-collapse:collapse;
            ">

                <tr style="
                    background:#E8EAF6;
                ">

                    <th style="padding:12px;">
                        Оқушы
                    </th>

                    <th style="padding:12px;">
                        Әлсіз кесте
                    </th>

                    <th style="padding:12px;">
                        Бастапқы
                    </th>

                    <th style="padding:12px;">
                        Кейін
                    </th>

                    <th style="padding:12px;">
                        Өзгеріс
                    </th>

                </tr>

                {rows}

            </table>

        </div>


        <div style="
            background:#E3F2FD;
            padding:20px;
            border-radius:17px;
            margin-top:18px;
            text-align:center;
            font-size:17px;
            line-height:1.6;
        ">

            🤖 <b>KobeitDos AI қорытындысы</b>

            <br><br>

            {ai_text}

        </div>

    </div>
    """


# ==========================================================
# СЫНЫП НӘТИЖЕСІ БЛОГЫ
# ==========================================================

class_result_full23 = widgets.VBox([
    class_result23,
    class_chart13
])

class_result_full23.layout.display = "none"


# Платформаға орналастыру
KobeitDos_AI.children = (
    app_title,
    student_box5,
    app_menu,
    home_box14,
    learn_box18,
    game_box17,
    diag_box19,
    practice_box20,
    result_full15,
    class_result_full23
)


print("✅ «Сынып нәтижесі» жаңа дизайны дайын.")

✅ «Сынып нәтижесі» жаңа дизайны дайын.

In [ ]:
# ==========================================================
# 📈 ЖАҢА «СЫНЫП НӘТИЖЕСІН» МӘЗІРГЕ БАЙЛАНЫСТЫРУ
# ==========================================================

# Алдыңғы мәзір әрекетін алып тастау
try:
    app_menu.unobserve(
        app_change22,
        names="value"
    )
except:
    pass


def app_change23(change):

    section = change["new"]

    # Барлық бөлімді жасыру
    home_box14.layout.display = "none"
    learn_box18.layout.display = "none"
    game_box17.layout.display = "none"
    diag_box19.layout.display = "none"
    practice_box20.layout.display = "none"
    result_full15.layout.display = "none"
    class_result_full23.layout.display = "none"


    if section == "home":

        home_box14.layout.display = ""


    elif section == "learn":

        learn_box18.layout.display = ""


    elif section == "game":

        game_box17.layout.display = ""
        game_start17()


    elif section == "diagnostic":

        diag_box19.layout.display = ""
        diagnostic_start2()


    elif section == "practice":

        practice_box20.layout.display = ""
        practice_start3()


    elif section == "result":

        result_full15.layout.display = ""
        result_box4.layout.display = ""

        # Оқушы атын енгізілген жолдан алу
        global student_name5
        student_name5 = student_input5.value.strip()

        show_result21()


    elif section == "class_result":

        class_result_full23.layout.display = ""

        # Жаңа сынып нәтижесі
        show_class_result23()

        # Бұрынғы салыстыру диаграммасы
        show_class_chart13()


# Жаңа мәзір әрекетін қосу
app_menu.observe(
    app_change23,
    names="value"
)


# Қазіргі бөлімді жаңарту
app_change23({
    "new": app_menu.value
})


print("✅ Жаңа «Сынып нәтижесі» мәзірге қосылды.")

✅ Жаңа «Сынып нәтижесі» мәзірге қосылды.

In [ ]:
# ==========================================================
# 🧹 ТЕСТ НӘТИЖЕЛЕРІН ТАЗАЛАУ
# ==========================================================

import pandas as pd

columns = [
    "Оқушы",
    "Әлсіз кесте",
    "Диагностика (%)",
    "Жаттығудан кейін (%)",
    "Өзгеріс (%)"
]

# Бос кесте жасау
clean_df = pd.DataFrame(columns=columns)

# Сол Excel файлына сақтау
clean_df.to_excel(
    file_path10,
    index=False
)

print("✅ Тест нәтижелері тазаланды.")
print("📊 Енді нақты оқушылардың нәтижелерін жинауға болады.")

✅ Тест нәтижелері тазаланды.
📊 Енді нақты оқушылардың нәтижелерін жинауға болады.